### ISSUE TITLE
Specialize for serializing to Vec<u8>

### ISSUE THREAD

**Issue by dtolnay** [bincode-org/bincode#120]
This would allow serialize_struct to use a heuristic to pre-allocate space in the vec based on the number of fields. In https://github.com/bitsparrow/bitsparrow-rust/issues/2#issuecomment-282100777 we discovered that this can increase serialization performance by a factor of 2.7 if done right.

**Comment by TyOverby** [comment]
When bincode has a size limit, it is forced to check the size of an encoded struct, so it'll do precise vec preallocation.  Is this what you're talking about?

https://github.com/TyOverby/bincode/blob/master/src/serde/mod.rs#L147

**Comment by dtolnay** [comment]
No, in the Infinite case [this function](https://github.com/TyOverby/bincode/blob/324dcb2050e98a3a9aeebb3b3e36d18f3bd0a2b8/src/serde/writer.rs#L152) could preallocate similar to what happens [here](https://github.com/bitsparrow/bitsparrow-rust/blob/4d819b6374dfdbea4628a6ec249715372e288186/src/encode.rs#L43). The heuristic they use is `8 * nfields` [here](https://github.com/bitsparrow/bitsparrow-derive/blob/49e2101a198a461a440bd9dadb488f664969d3a3/src/encode.rs#L26).

**Comment by TyOverby** [comment]
so while they're visiting instances of structs, they're modifying the Vec allocation?

**Comment by TyOverby** [comment]
err, what happens in this instance:

```
encode(vec![MyStruct{ x: sdfsdfs, y: sdfsjdfsdf}, MyStruct{x: fkljasdflkjasdf, y :sklsjdlksjd}])
```

are there two calls to adjust the allocation?

**Comment by dtolnay** [comment]
It looks like in their case it only happens once at the beginning, so if you call `encode` and pass a struct containing 6 fields, it will preallocate a guess of `8 * 6` bytes for the output. The Vec case looks like [it does not preallocate at all](https://github.com/bitsparrow/bitsparrow-rust/blob/4d819b6374dfdbea4628a6ec249715372e288186/src/encode.rs#L510).

We should experiment with a couple different heuristics to see what works best for Bincode. 270% performance is too much to leave on the table. It would be a good idea to establish a benchmark suite that we trust first #112.

**Comment by TyOverby** [comment]
I think benchmarking would be a good idea.  However, I think this is a post-1.0 change as the workaround is too easy: encode into a Vec that has already been preallocated with the "encode into `Write`r" bincode api.

**Comment by maciejhirsz** [comment]
For things like `Vec<Foo>` there is dynamic allocation happening before the size prefix is being written, it will allocate (reserve) roughly `bytes_for_prefix + length_of_vec * Foo::size_hint()`.

The current logic of 8 * field count for structs is a placeholder, the allocation can be made more precise than this, though even that already is good enough of an optimization to remove a large bulk of reallocations.

**Comment by TyOverby** [comment]
I'm pretty sure that we can adjust my already-existing routines for determining object size and with a few tweaks make it heuristic-based (and faster).  

I've added this to the post-1.0 milestone with a dependency on the benchmarking system.
