### ISSUE TITLE
Convenience API for skipping data?

### ISSUE THREAD

**Issue by Gankra** [bincode-org/bincode#154]
I'm working on a format where I have several arrays in my data stream that I don't want to deserialize right away, but instead jump over and deserialize on demand later (element-by-element).

It would be nice if there was methods like:

```
// returns bytes skipped over
bincode::skip_over<T: Deserialize>(&mut Reader, count: usize) -> Result<usize>;
```

Bincode might be able to implement this better than I could naively, by using things like fixed-serialized-size info to skip over everything without any parsing in O(1). In general this API needs to parse (enums), but it can basically be like "it only parses as much as is needed to skip over the data".

**Comment by samlh** [comment]
https://serde.rs/ignored-any.html may be relevant

**Comment by Gankro** [comment]
I'm using bincode, so I need to give the fields a type.

**Comment by Xaeroxe** [comment]
@Gankro serde 1.0 introduces zero copy deserialization, so as soon support for 1.0 is finished you should be able to use that to similar effect.

**Comment by Gankro** [comment]
Zero copy deserialization only works on bytes and strs; my slices contain actual types that need to be materialized into a new buffer.

**Comment by Xaeroxe** [comment]
I see.  Well in the mean time maybe you could use borrowed_bytes with a wrapper struct and interpret the bytes lazily when needed?  I'm not sure if that's easy or doable I'm just thinking out loud.

**Comment by TyOverby** [comment]
@Xaeroxe: that's what I suggested in #serde a few days ago.  Unfortunately it would require serializing extra "length" bytes into the output, so for lots of tiny structs this isn't an option.

**Comment by Xaeroxe** [comment]
Hmm I wonder if it's possible to do this using generics do the length is coded into the executable rather than the memory representation.  I might look into that.
