### ISSUE TITLE
Support serializing to Vec<u8> with unknown seq/map length

### ISSUE THREAD

**Issue by dtolnay** [bincode-org/bincode#167]
When the sequence is done it should go back and write the length in the correct spot.

Though variably encoding the length may make this less feasible - cc #75.

**Comment by arthurprs** [comment]
Is that a problem in practice? I think the majority of binary serialization formats have problems supporting unknown lengths.

**Comment by TyOverby** [comment]
I'm not sure how useful this.  How many people encode using different types than they decode?

**Comment by JoshMcguigan** [comment]
If I'm understanding this suggestion correctly, it would resolve #245. I thought this could be implemented by tracking the index into our underlying `vec` when creating a `Compound`, then going back and updating the appropriate size at that starting index in the `vec` during the `SerializeMap::end` method. 

The trouble is all of the serialization methods in bincode are generic over the std::Write trait, which doesn't allow the type of access we need into the underlying vec. I'm not sure if there is a better way to handle this? Or if perhaps there are additional trait bounds that would help here without limiting the API too much?

**Comment by MTRNord** [comment]
Any Idea when this will get  any kind of fix? :(

**Comment by ZoeyR** [comment]
@MTRNord so far there has not been a proposed solution that does not come with significant drawbacks. Implementing this is held up until we can identify an implementation that doesn't come with those drawbacks.

**Comment by mitsuhiko** [comment]
This issue should be reopened. It's still a big problem, particularly when working with structs involving serde's `flatten` feature.

**Comment by nmccarty** [comment]
We have decided to declare this issue out of scope. 

Bincode only officially supports types that serialize to a known length, and the initial proposed solution of going back and rewriting the correct length after serializing the sequence both causes issues with varint encoded lengths, and can not be made general as it can not be assumed that any given writer supports `Seek`, and specializing for `Vec<u8>` would incur unacceptable performance penalties for common usecases.
