### ISSUE TITLE
Error building Example code in Readme

### ISSUE THREAD

**Issue by ltfschoen** [bincode-org/bincode#251]
if I create a new project with
```
cargo new bincode_test;
cargo install cargo-edit;
cargo add bincode serde_derive;
cd bincode_test;
```
And then replace the contents of bincode_test/src/main.rs with the [Example](https://github.com/TyOverby/bincode#example) code from the README.md. 

Then when I try to build the code with:
```
cargo build
```
It gives error:
```
error[E0463]: can't find crate for `_serde`
 --> src/main.rs:7:21
  |
7 | #[derive(Serialize, Deserialize, PartialEq, Debug)]
  |                     ^^^^^^^^^^^ can't find crate
```

System:
cargo 1.29.0 (524a578d7 2018-08-05)
rustc 1.29.1 (b801ae664 2018-09-20)

**Comment by TyOverby** [comment]
`cargo add serde`

**Comment by jounathaen** [comment]
Same problem here. I could fix it by adding
```rust
#[macro_use]
extern crate serde_derive;
```
To the example

**Comment by robinmoussu** [comment]
I had more or less the same issue. I solved it with adding in my Cargo.toml

```toml
[dependencies]
bincode = "1.2"
serde =  { version = "1.0", features = ["derive"] }
```
