### ISSUE TITLE
no_std support

### ISSUE THREAD

**Issue by akhilles** [bincode-org/bincode#265]
Is it possible to add an unstable-only `no_std` feature that uses `alloc` and `core_io`?

**Comment by fadeevab** [comment]
Would love to see this feature as well.

**Comment by emmanuelantony2000** [comment]
I am currently looking at this, for serde to support no_std with allocations nightly Rust is required, and moreover Read and Write traits need std, unless we use something like core_io or any alternatives. So should I proceed with this??

**Comment by ZoeyR** [comment]
It also may not be possible without a breaking change. To add no_std support we need to add a new default feature, which would break people who build without default features.

**Comment by akhilles** [comment]
> I am currently looking at this, for serde to support no_std with allocations nightly Rust is required, and moreover Read and Write traits need std, unless we use something like core_io or any alternatives. So should I proceed with this??

`liballoc` is stable now, so nightly shouldn't be required. For `Read` and `Write` traits, I would mimic capnproto-rust's approach: https://dwrensha.github.io/capnproto-rust/2020/06/06/no-std-support.html. These are the custom `no_std` I/O traits that they define: https://github.com/capnproto/capnproto-rust/blob/master/capnp/src/io.rs.

**Comment by emmanuelantony2000** [comment]
@ZoeyR what if we introduce no_std, but keep the external api completely same? Now the parent program can be std or no_std, but bincode will be no_std.

Hey @akhilles, yeah I feel the Cap'n proto's approach is good. Should I start working on it?

**Comment by ZoeyR** [comment]
@emmanuelantony2000 without a feature there is no way to keep the external api the same since it relies on types not present in core.

**Comment by Manishearth** [comment]
This probably can be reopened: The `alloc` crate exists, and `serde_json`/`serde` already do this. The annoying thing with bincode is that the config types depend on `std::io`, so we probably should follow the capnproto approach.

**Comment by esden** [comment]
Any chance of this issue being reopened? It would be really nice to be able to use bincode on embedded targets.

**Comment by VictorKoenders** [comment]
This will be a #1 priority in bincode 2, which is slowly being worked on.

The latest [2.0.0-rc](docs.rs/bincode/2.0.0-rc/) should be usable on embedded systems
