### ISSUE TITLE
Serialization in other languages

### ISSUE THREAD

**Issue by NN-Binary** [bincode-org/bincode#266]
Hi,

Anyway you can provide an example to do the ser in Javascript?
Would be awesome for Rust servers.

Thanks man!

**Comment by TyOverby** [comment]
You could compile a Rust program to webassembly and do it there?

Otherwise, I'd recommend using Serde with msgpack or bson

**Comment by ZoeyR** [comment]
I'm turning this into a tracking issue for serialization in other languages. Here are the languages I would like to see:

- [ ] C++
- [ ] Javascript
- [ ] C#
- [ ] Java

Feel free to suggest more

**Comment by mindv0rtex** [comment]
How about Python?

**Comment by ZoeyR** [comment]
I don't have any experience in python, but that would be a good thing to see this in! Once I have a spec written I can also get help from the community to write implementations.

**Comment by CRRRRR2016** [comment]
Hi, I want to have communication between two micro-servers, but one of them is based on rust and the other is based on go.How can I deserialize the messages from the rust server and serialize the messages I have to send to rust server by go ?
