### ISSUE TITLE
Deserialize implementations for primitives do not optimize well

### ISSUE THREAD

**Issue by saethlin** [bincode-org/bincode#334]
I've been optimizing Redjack's `Deserialize` impls which we use with bincode. At the moment some of our key benchmarks are spending ~13.5% of their cycles in the `bincode` deserializer impls for `u8`, `u32`, and `u64`. It looks to me like we could make a dent in this number by adding `forward_read` methods to `BincodeRead` for all (or most) of the other `serde` primitives.

I am interested in contributing a patch that makes this happen. Is there anything a first-time contributor should know?

**Comment by ZoeyR** [comment]
`BincodeRead` is a public trait so keep that in mind. Any new methods will need default impls
