### ISSUE TITLE
Missing GitHub releases for 1.3.0 and 1.3.1

### ISSUE THREAD

**Issue by bgilbert** [bincode-org/bincode#338]
GitHub doesn't have [tags](https://github.com/servo/bincode/tags) or [changelogs](https://github.com/servo/bincode/releases) for Bincode 1.3.0 or 1.3.1.

**Comment by badboy** [comment]
I second this. Would it be possible to add at least 1.3.1 after the fact?
Looks like 1.3.1 was done as part of a bug fix commit here: https://github.com/servo/bincode/pull/336
1.3.0 got its own commit here: https://github.com/servo/bincode/commit/439b12dbcba903b7681879f96f932dc20b0a5115

**Comment by yerke** [comment]
@ZoeyR Could you help please?
