### ISSUE TITLE
Unable to deserialize enums with value gaps

### ISSUE THREAD

**Issue by kiwidoggie** [bincode-org/bincode#358]
Provided the enum 
```
`pub enum CXmlMagic {
    None = 0,
    One = 0x464F4352
}
```

and including it in another struct, when I try and use bincode::deserialize on that struct, I get this error

`could not deserialize invalid value: integer 1179599698, expected variant index 0 <= i < 2.`

It seems like because it tries and use the number of values as the max instead of the actual values inside. Am I mis-using bincode somehow, or should I need tags somewhere? I'm not familiar with rust and don't know if this is intended or a bug with bincode's library.

**Comment by ZoeyR** [comment]
I'll look into this. It might be a bug in bincode _or_ a bug in the derivation of serialize/deserialize
