### ISSUE TITLE
Dataloss using deserailise() or deserialize_from()  with a TcpStream

### ISSUE THREAD

**Issue by thegatsbylofiexperience** [bincode-org/bincode#361]
Hi,

I've been playing with bincode for a message passing library I have been creating.

I have come upon a data loss bug in regards to how bincode deserialises data (It might not be just bincode, I am not well versed in SerDe).

With a TcpStream connection the buffer may have multiple messages in it if the receiver is slow to act upon receiving data.

if one is to run a read and then deserialise on a buffer with multiple messages in it. bincode will deseerialise the first message successfully and not return any errors. 

Doing the same thing with deserailize_from(TcpStream) incurs the same problem -- it reads the entire buffer, deserialises the first message and discards the rest.

To me this is a correctness issue. As I am reliant on bincode to tell me the contents of my buffer. It should be telling me of an issue (in the case of deserialize()). Or at least how much is read. So I can make a decision on what to do with the rest.

In the case of deserialize_from() I would say that the function should be peeking at the data, finding out how much is part of a single message and only reading that amount from the buffer. The rest being left for the next call. This however will not work as peek is a TcpStream abstraction and not part of the Read trait. As such this should return an error with the buffer and allow for deserialize() to be used on the multiple messages.

Thanks.

**Comment by ZoeyR** [comment]
I'm not sure how `deserialize_from` is misbehaving in your case, can you construct a minimal reproduction?. `deserialize_from` shouldn't be reading any extra data in the read object.

**Comment by thegatsbylofiexperience** [comment]
Hiya,

I'm going to have to sheepishly say that deserialize_from is behaving with TcpStream. My 4am-sleep-deprived-mind that caused the issue. I missed a code path. I am very sorry for wasting your time.

With regards to the issue with deserialise maybe some documentation to push future newcomers towards serialize_from might help.

Happy to make a PR if you would like.

Please let me know.

Thank you for your time.

**Comment by VictorKoenders** [comment]
More documentation is always welcome, feel free to make that PR if you still have time
