### ISSUE TITLE
Is there any way to serialize a Vec<T> without also serializing the length of the Vec?

### ISSUE THREAD

**Issue by mcronce** [bincode-org/bincode#369]
Thus far I've tried using `#[serde(serialize_with)]` to point to a function that just serializes the items individually (only worrying about `Vec<u8>` at this time, possibly only ever), but have not had luck there.

The use case is that I'm implementing a wire protocol whose header already includes a length, and for several of the message types, there's an "other data" bucket that's just "however many bytes are leftover after you subtract the fixed-length fields", so I've got no need to include the length of the `Vec` itself.  I also don't control the protocol, unfortunately, so I can't just say "this is dumb, add the length" :)

Thanks!

**Comment by mcronce** [comment]
Hah, I was able to hack around it by using `.serialize_tuple()` in my `serialize_with` function.  If there's a better way (from a semantics/clarity standpoint) I'm super open to it, but this does at least _work_.

**Comment by JMS55** [comment]
Maybe try `Box<[u8]>`?, which can be gotten from a `Vec<u8>` by doing `v.into_boxed_slice()`.
