### ISSUE TITLE
Deserialize a serde_json::Value

### ISSUE THREAD

**Issue by lucassardois** [bincode-org/bincode#374]
It looks like bincode is not able to serialize a struct containing fields of type serde_json::Value.
For instance the following example:
```rust
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Serialize, Deserialize)]
struct Test {
    value: Value,
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    #[test]
    fn test() {
        let t = Test { value: json!("{}") };
        let ser = bincode::serialize(&t).unwrap();
        let de: Test = bincode::deserialize(&ser).unwrap();
    }
}
```

Produces this error:
```
 panicked at 'called `Result::unwrap()` on an `Err` value: DeserializeAnyNotSupported'
```

Any idea how to solve this issue? Or is bincode not suited for this kind of usecase?

**Comment by ghost** [comment]
Bincode is not a self-describing format which makes it not compatible with `serde_json::Value`. This is a fundamental limitation and so far there hasn't been a proposed solution.
