### ISSUE TITLE
problematic byteorder version

### ISSUE THREAD

**Issue by ZijianHe** [bincode-org/bincode#381]
Should probably undo [this change](https://github.com/bincode-org/bincode/commit/8076aee4ba7fe1904e71457e4e9578abccab83e3#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R19) since this change basically prevents people using a higher version of Rust from directly or indirectly having a higher version of byteorder in their dependencies. 

In my case I've got this error: 

```
Caused by:
  failed to select a version for `byteorder`.
      ... required by package `bincode v1.3.2`
      ... which is depended on by `xxxxxx`
  versions that meet the requirements `>=1.3.0, <1.4.0` are: 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0

  all possible versions conflict with previously selected packages.

    previously selected package `byteorder v1.4.2`
      ... which is depended on by `rmp v0.8.10`
      ... which is depended on by `rmp-serde v0.15.4`
      ... which is depended on by `xxxxxx`

  failed to select a version for `byteorder` which could resolve this conflict
```

**Comment by VictorKoenders** [comment]
See #380 for more information on this

Currently bincode supports rust 1.18 and up, and byteorder released a version that is not compatible with this. We're working on a (breaking) change version that has a higher minimum rust version that fixes this.
