### ISSUE TITLE
 value: DeserializeAnyNotSupported'

### ISSUE THREAD

**Issue by vedantroy** [bincode-org/bincode#386]
I serialize a `serde_json::Value` to binary using bincode, but when I deserialize it, I get a crash with error: "value: DeserializeAnyNotSupported".

What does this mean?

**Comment by vedantroy** [comment]
Note: This is mostly a curiosity question, I'm refactoring my code to serialize a normal struct.

**Comment by VictorKoenders** [comment]
Bincode is not self-describing like JSON is, so we do not have a way to find out what data type a value is.
With json you can make a guess, like:
```json
{ "a": 3 }
```
Which is some form of numeric type.
In bincode you simply have a byte array with no identification in front, and bincode depends on the data structure to be valid to parse the data.
