### ISSUE TITLE
Provide more explicit guidance on which options are best for new projects

### ISSUE THREAD

**Issue by TedDriggs** [bincode-org/bincode#395]
As someone who's adding `bincode` to a new project, I'm having a hard time figuring out from docs what the "right" way to use the crate is.

Most of the documentation uses the `serialize` and `deserialize` functions, as does the example. That works great.

My use-case involves writing serializing a list of things, then reading them out again later. Due to #387, I added a `BincodeDevice<'a>` struct that borrows from `Device<'a>` to do the actual serialization. I then have this:

```rust
impl<'a> Device<'a> {
    pub fn to_bincode(&'a self) -> BincodeDevice<'a> {
        // elided
    }
}
```

I then call `devices.iter().map(Device::to_bincode)`, and rather than collecting that into a `Vec`, I decided to use `serde::Serializer::collect_seq`. That's when I found `bincode::Serializer::new(...)`, which is when things started getting harder.

The docs do warn that the function form and the `DefaultOptions` form have different settings - thanks for being very explicit about that, and for providing clear guidance on how to get the function behavior with the struct. However, reading [this sentence](https://docs.rs/bincode/1.3.3/bincode/config/index.html#options-struct-vs-bincode-functions) left me wondering which settings I _should_ be using.

> Due to historical reasons, the default options used by the `serialize()` and `deserialize()` family of functions are different than the default options created by the `DefaultOptions` struct

The phrase "historical reasons" makes me think the new way is better, but that's never actually stated. It would be helpful if the docs were slightly more opinionated, or provided some pros and cons on the different settings.

**Comment by adsick** [comment]
I personally would like more bincode/examples, I see there only 3yrs old basic example and it makes me think, that the crate is abandoned, because nearly all Rust crates have examples in them, that's what Rust philosofy is.
