### ISSUE TITLE
Get length of serialized `Vec<T>`

### ISSUE THREAD

**Issue by joshbenaron** [bincode-org/bincode#398]
Hey,
Is there a way to get the length of a `Vec<T>` without deserializing back to `Vec<T>` and doing `Vec::len()`? I notice they serialize with 8 bytes padding. I assume that represents the length. If I knew the scheme I could handle myself.

**Comment by ghost** [comment]
Yes, `Vec<T>`s are prefixed with their length encoded as a `u64`. The specifics of how the `u64` are encoded (fixint/varint, bigendian/littleendian) are determined by the bincode settings.
