### ISSUE TITLE
Using Box<dyn bincode::Options> results in compiler error

### ISSUE THREAD

**Issue by surban** [bincode-org/bincode#399]
Hi,

I need to pass Bincode options to a function without using generics. However, when I try to use the function signature

`fn test(config: Box<dyn bincode::Options>)`

the compiler complains with:

    the value of the associated types `Endian` (from trait `config::internal::InternalOptions`), `IntEncoding` (from trait `config::internal::InternalOptions`), `Limit` (from trait `config::internal::InternalOptions`), `Trailing` (from trait `config::internal::InternalOptions`) must be specified`.

Could someone please point me in the right direction?

Thanks!

**Comment by tv42** [comment]
The way Options is implemented, with tons of generic types, makes it very cumbersome. My use case: I wanted to store it in `lazy_static!` so I can easily use the same options in all serialize/deserialize calls in my library.

Even if I had a "context" type where I could store the value, what's the type of the field? The generic stuff gets really messy.

Even if I let go of the idea of *storing* the options, how do I write a helper function to avoid copy-pasting the options builder? The return type would be quite nasty.

**Comment by nmccarty** [comment]
This usage is unfortunately not currently supported. The `Options` system uses types, instead of values, to encode the options in order to be able to avoid branches on hot paths when encoding/decoding. This is possible to do in a more elegant and trait-object friendly way on more modern Rust, but the low MSRV for the 1.x.x family of bincode releases limits our options (pun not intended).

**Comment by surban** [comment]
As a stop-gap measure could we un-deprecate the `Config` struct until a way is found to support this usage scenario with the new `Options` system?

**Comment by nmccarty** [comment]
Would you mind answering a question so we can better understand your usecase:

Why exactly are you trying to pass the options into a method as a trait object? Are you trying to dynamically alter the serialization/deserialization behavior at run time, or are you just trying to avoid having to deal with constructing the options object?

**Comment by tv42** [comment]
My use case is I'm afraid if I copy-paste the `bincode::options().with_foo().with_bar().with_baz()` logic into every place that needs it, 6 months later I'll fail to keep them in sync. And there seems to be no clean way of sharing the value of expression, nor putting it in a common helper function.

**Comment by nmccarty** [comment]
@tv42 For your use case, it seems like it would be more appropriate to use a type alias for your options, or just define a set of methods like 
```rust
pub(crate) fn deserialize<'a, T>(&self, bytes: &'a [u8]) -> Result<T>{
    bincode::DefaultOptions::new().deserialize(bytes)
}

pub(crate) fn serialize<S: ?Sized + Serialize>(self, t: &S) -> Result<Vec<u8>> {
    bincode::DefaultOptions::new().serialize(t)
}
```

**Comment by tv42** [comment]
I have those two functions. That still repeats the options building, but only once.

I just tested this to work, too:

```rust
    type MyBincodeOptions = bincode::config::WithOtherEndian<
        bincode::config::WithOtherIntEncoding<
            bincode::config::WithOtherTrailing<
                bincode::config::WithOtherLimit<
                    bincode::config::DefaultOptions,
                    bincode::config::Bounded,
                >,
                bincode::config::RejectTrailing,
            >,
            bincode::config::VarintEncoding,
        >,
        bincode::config::BigEndian,
    >;
    lazy_static! {
        static ref BINCODE_OPTIONS: MyBincodeOptions = bincode::DefaultOptions::new()
            .with_limit(10000)
            .reject_trailing_bytes()
            .with_varint_encoding()
            .with_big_endian();
    }
```

Now I'm *still* repeating the options, in different formats, but at least the compiler will yell at me if I get it wrong. It sure ain't pretty, though!

**Comment by nmccarty** [comment]
To your first point, yes it does still technically repeat the options, but that is idiomatic usage, [and I don't believe the desire to only say things once is productive in this case](https://users.rust-lang.org/t/rust-koans/2408/4). If you are concerned about making sure that your options are compatible everywhere, might I suggest a simple round trip unit test? 

I will admit to the long type signatures being a bit ugly, but, and i was corrected by another maintainer on this, this type-based approach is actually required to _guarantee_ keeping the branches out of the hot path, and is a small price to pay for such.
