### ISSUE TITLE
How to combine varints with regular fixed ints?

### ISSUE THREAD

**Issue by sparkplug0025** [bincode-org/bincode#415]
I'm consuming a service where it expects a structure with fields that have variable length ints (varints) and also fixed size ints. 

Example:
```rs
#[derive(Serialize, Deserialize, Eq, PartialEq, Debug)]
struct ServiceRequest {
  field_a: u32, // --> this is a fixed lenth uint32
  field_b: u32, // --> this is a variable length uint32
}
``` 

My issue is that bincode varint config is global. What is the best way combine both?

I was going down this path but I found lots of complexities due to Serializer having a fixed set of types:
```rs
struct VarUint32(u32);

impl Serialize for VarUint32 { ... } // implements a custom varint serialization here

#[derive(Serialize, Deserialize, Eq, PartialEq, Debug)]
struct ServiceRequest {
  field_a: u32,
  field_b: VarUint32,
}
```

Any simple solution or suggestions around it?

**Comment by VictorKoenders** [comment]
There is currently not a simple solution for this. The way you described is the only way to do customized (de)serialization behavior.

I would suggest making a wrapper for the `FixIntU32` and let bincode (de)serialize your struct with varint, as the fixed int encoding is a lot simpler.

**Comment by VictorKoenders** [comment]
Something like this might work: (untested)

```rust
struct FixIntU32(u32);

impl Serialize for FixIntU32 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        var bytes = self.0.to_be_bytes(); // or .to_le_bytes();
        for b in bytes.iter().copied() {
            b.serialize(serializer)?;
        }
    }
}
```

**Comment by ghost** [comment]
Bincode is not designed to interop with other serialization formats. What type of varints does this service expect? Are they the same varints as bincode?

**Comment by sparkplug0025** [comment]
@ZoeyR yes they fortunately are.

@VictorKoenders thanks for the idea! (I see a problem in your code since the serializer is being moved inside the loop, but I got the general idea! Thanks for that 🙏 )
