### ISSUE TITLE
the trait `std::error::Error` is not implemented for `EncodeError`

### ISSUE THREAD

**Issue by vadixidav** [bincode-org/bincode#429]
Currently, the `Error` trait from `std` is not implemented on `EncodeError`. This makes the new alpha unwieldy to use. The trait should be implemented if the `std` feature is enabled.

**Comment by VictorKoenders** [comment]
This will be fixed with #422 and should be in alpha.1

**Comment by VictorKoenders** [comment]
This has been implemented in v2.0.0-alpha.1
