### ISSUE TITLE
Documentation around Serializing/Deserializing as different types

### ISSUE THREAD

**Issue by GrantJamesPowell** [bincode-org/bincode#437]
Howdy! Thanks for making this library, it's super neat.

I'm writing a network protocol and I'm wondering if the following is a supported use case/an accident. (I'd include a rust playground link, but `bincode` isn't part of the playground)

The gist is that I'd like to serialize values of `ProtocolMsg::Error` as `Protocol<()>` and have the client Deserialize it as a `ProtocolMsg<T>`. It seems to *_work_*, but I'm wondering if I'm breaking some unspoken invariant of the library.

```
#[cfg(test)]
mod tests {
    use serde::{Serialize, Deserialize};

    #[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
    enum ProtocolMsg<T> {
        Msg(T),
        Error(String),
    }

    #[derive(Debug, PartialEq, Eq, Serialize, Deserialize)]
    struct SomeType;

    #[test]
    fn test_serialization_and_deserialization_as_different_types() {
        // Serialize the Error Variant into a ProtocolMsg<()>
        let err: ProtocolMsg<()> = ProtocolMsg::Error("foo".to_string());
        let serialized = bincode::serialize(&err).unwrap();

        // Will it _always_ work if I deserialize ProtocolMsg<()> with ProtocolMsg<T>?
        // How do I begin to answer that question? Will my mileage vary between bincode/serde_json/etc...?

        assert_eq!(
            ProtocolMsg::Error("foo".to_string()),
            bincode::deserialize::<ProtocolMsg<u64>>(&serialized).unwrap()
        );
        assert_eq!(
            ProtocolMsg::Error("foo".to_string()),
            bincode::deserialize::<ProtocolMsg<String>>(&serialized).unwrap()
        );
        assert_eq!(
            ProtocolMsg::Error("foo".to_string()),
            bincode::deserialize::<ProtocolMsg<SomeType>>(&serialized).unwrap()
        );
    }
}
```

**Comment by ghost** [comment]
This is totally fine to do according to the spec. Since you're only ever serializing the `Error` variant the encoded data will be the same regardless of the value of `T`. Although I'm curious about the reason you need to do it this way?

**Comment by GrantJamesPowell** [comment]
Thanks for the answer! I was going down a _too_ complicated path with generics and I ended up going a different direction rendering the question moot for my project. Thank you though!
