### ISSUE TITLE
efficient (de)serialization of a sequence of non-owned data structures

### ISSUE THREAD

**Issue by gertjanvanzwieten** [bincode-org/bincode#440]
I would like to use bincode to send an open-ended sequence of individually serialized objects over a socket. While I could use `serialize_into` and `deserialize_from` and call it a day, this forces me to created owned data structures (holding String), adding memory allocations on both sides of the socket - one for creating the structure prior to serialization, the other for recreating the structure. While I could improve on the sending side by reusing buffers, the same does not appear possible on the receiving end.

Instead I would prefer serializing directly from borrowed data (holding str) and using zero-copy deserialization, using `deserialize` rather than `deserialize_from`. Ideally I would like bincode to announce how many bytes to read for the upcoming object, but I suspect the encoding does not allow for this. Failing that, I would consider using `VecDeque` with an occasional `make_contiguous`. However, even when trailing bytes are allowed, `deserialize` does not report how many bytes were consumed.

Is there a way to make deserialization of a sequence of non-owned data structures work in bincode, either in 1.x or in the upcoming 2.0? If not, is there any way of avoiding repeated allocations in the deserialization of a sequence of owned data structures?

**Comment by VictorKoenders** [comment]
In bincode 2  you can do something like

```rs
#[derive(bincode::BorrowDecode, bincode::Encode, PartialEq, Debug, Eq)]
pub struct Test3<'a> {
    a: &'a str,
    b: u32,
    c: u32,
}

fn main() {
   let start = Test3 {
        a: "Foo bar",
        b: 10u32,
        c: 1024u32,
    };
    let mut slice = [0u8; 100]; // can also be a Vec<u8>, must be pre-allocated

    let len = bincode::encode_into_slice(&start, &mut slice, Configuration::standard()).unwrap();
    let end: Test3 = bincode::decode_from_slice(&slice[..len], Configuration::standard()).unwrap();
    assert_eq!(end, start);
}
```

As for the deserialize not reporting how many bytes consumed, most systems I've used send a length before sending the rest of the packet. This will be protocol-specific (e.g. storing to disk does not need this) and is thus not supported by bincode by default.

Something like:
```rs
let mut slice = [0u8; 1024];
// encode the packet at fixed offset 4
let len = bincode.encode_into_slice(&mut slice[4..], your_packet, Configuration::standard()).unwrap();
// encode the # of bytes written to the first bytes
bincode.encode_into_slice(&mut slice[..4], len as u32, Configuration::standard()).unwrap();
```

Does this work for you?

**Comment by gertjanvanzwieten** [comment]
Indeed, adding a header should work. I did briefly consider going down this path but didn't feel good about it as it is technically duplicating information that is already encoded in the stream - though I realize that that is just not very pragmatic and perhaps redundancy is a good thing. Thanks for pointing the way and for the helpful examples, much appreciated!
