### ISSUE TITLE
Support `skip`/`skip_encoding`/`skip_decoding` field attributes

### ISSUE THREAD

**Issue by songzhi** [bincode-org/bincode#452]
Like `#[serde(skip)]`/`#[serde(skip_serializing)]`/`#[serde(skip_deserializing)]`.

I think it's useful because of the lack support for `AsyncWrite`/`AsyncRead` in current bincode crate. 

For example, I hava a `Message` struct with a `large_data` bytes slice. 
```rust
use bincode::Encode;

#[derive(Encode)]
struct Message<'a> {
    x: u32,
    y: u32,
    z: u32,
    #[bincode(skip_encoding)]
    large_data: &'a [u8]
}
```
I want to send it to a `AsyncWrite` impl like `tokio::net::TcpStream`. And I want encode it into bytes without the `large_data`,  so I can write the encoded bytes firstly, then write the `large_data` directly to the `TcpStream` without `memcpy`.  And I want it could be borrow-decoded entirely. I know that using a `std::io::BufWriter` could do this automatically and perfectly, but for `AsyncWrite` impls, I have to manually write these logics.

So I think `skip_encoding` field attribute is a solution? Unless the bincode crate doesn't want to implement this feature.

**Comment by VictorKoenders** [comment]
I don't think we want to implement `skip` attribute. There are many known issues with `serde`'s skip attributes: [docs.rs](https://docs.rs/bincode/2.0.0-alpha.1/bincode/serde/index.html#known-issues).

Additionally currently bincode ensures that encoding and then decoding a type will result in the exact same type. In other words:
```rust
let t: T = ...;
let vec = encode_to_vec(&t, config).unwrap();
assert_eq!(decode_from_slice(&vec, config).unwrap(), t);
```

If you want to do behavior like this, a couple of possible solutions come to mind:


You can split your `Message`:

```rust
struct Message<'a> {
    x: u32,
    y: u32,
    z: u32,
    large_data: &'a [u8]
}

#[derive(Encode)]
struct MessageHeader {
    x: u32,
    y: u32,
    z: u32,
}

impl<'a> Message<'a> {
    pub fn split(self) -> (MessageHeader, &'a [u8]) {
        (MessageHeader { x: self.x, y: self.y, z: self.z }, self.large_data)
    }
}

let (header, bytes) = message.split();
stream.write(bincode::encode_to_vec(&header, config).unwrap()).unwrap();
stream.write(bytes).unwrap();
```

Or you can implement a custom `Encode` trait

**Comment by songzhi** [comment]
I think the split solution is good, thanks.
