### ISSUE TITLE
explicit enum discriminant value

### ISSUE THREAD

**Issue by tguichaoua** [bincode-org/bincode#458]
The `Encode` and `Decode` macros use the variant index as discriminant. Adding an attribute to explicitly define wich value is used by each variants bring more control on encode/decode process.

Could be replaced by the [`arbitrary_enum_discriminant`](https://github.com/rust-lang/rust/issues/60553) in the future, when stabilized.

```rs
#[derive(Encode, Decode)]
enum Foo {
    #[variant(3)]
    A(u32),
    #[variant(5)]
    B(String)
}
```

**Comment by VictorKoenders** [comment]
Why would you want to specify the enum variant value? Is there a situation where the sequence index isn't good enough?

**Comment by tguichaoua** [comment]
The basic example I have in mind is a simple communication protocol where the firsts bits encode the command to use and other bits are for payload. I think the combinaison of bincode and enums is a pretty good to abtract this kind of problem.
Now imagine that, for some reason, some range of command number are reserved for future use:

| command  | number | payload  |
|----------|--------|----------|
| ping     | 0      | N/A      |
| pong     | 1      | N/A      |
| print    | 2      | String   |
| reserved | 3-50   |          |
| foo      | 51     | u32, u32 |

Also, explicit discriminant ensure we correctly fit the protocol.

**Comment by tguichaoua** [comment]
Now i'm thinking about it, the discriminant is always encoded as `u32` (which fit the majority of case), but in my above example a simple `u8` could do the job.
Maybe by using an optional attribute `#[discriminant(size)]` on the enum where `size` is either `u8`, `u16`, `u32`, `u64` or `u128`.

**Comment by VictorKoenders** [comment]
I think we want to keep `bincode-derive` as minimal as possible, so at the moment we don't want to add this.

Your case could be implemented by manually implementing `Encode` and `Decode`. If you check your `target` folder, you'll see `Foo_Encode.rs` and `Foo_Decode.rs`. This should give you a good indication on how to get started. Of course you could implement your own macro to auto-generate `Encode` and `Decode`.

Note that as described in the [specs](https://github.com/bincode-org/bincode/blob/trunk/docs/spec.md), enums are encoded by their index. You can easily expand your protocol by simply adding the new variants at the end and having a rule to never append an entry at the start.

The `arbitrary_enum_discriminant` feature has been open for 2 years now and there doesn't seem to be much activity, so I don't expect this to be stabilized any time soon.

> the discriminant is always encoded as u32

If you use [varint encoding](https://docs.rs/bincode/2.0.0-alpha.2/bincode/config/struct.Configuration.html#method.with_variable_int_encoding), your variant will be encoded in the smallest possible size. This will almost always be a `u8`, but will scale automatically if you go above 251 entries.
