### ISSUE TITLE
Respect user-provided repr for enums

### ISSUE THREAD

**Issue by mattfbacon** [bincode-org/bincode#460]
In the following enum declaration...

```rust
use bincode::{Encode, Decode};
#[derive(Encode, Decode)]
#[repr(u8)]
enum MyEnum {
    Foo = 3,
    Bar = 5,
    Baz
}
```

...none of the explicitly specified parameters (repr and variant values) are respected. Instead, the enum variant is (de)serialized as a u32, and Foo = 0, Bar = 1, Baz = 2.

**Comment by VictorKoenders** [comment]
Bincode should respect the C-style enums. See this [test](https://github.com/bincode-org/bincode/blob/trunk/tests/derive.rs#L169-L216). Can you make a minimal reproduction of your code that encodes wrongly?

We're not interested in respecting `repr` at the moment. With the `varint` configuration (which is default in bincode 2's `::standard()` config), all enums will be encoded as a `u8` anyway. We haven't had a good enough reason to change this in the [spec](https://github.com/bincode-org/bincode/blob/trunk/docs/spec.md) so far.

**Comment by VictorKoenders** [comment]
Just tested this code and it seems to pass and encode as a single byte.

```rs
#[derive(bincode::Encode, bincode::Decode)]
#[repr(u8)]
enum MyEnum {
    Foo = 3,
    Bar = 5,
    Baz
}

#[test]
fn test_my_enum() {
    fn ser(e: MyEnum) -> u8 {
        let mut slice = [0u8; 10];
        let bytes_written =
            bincode::encode_into_slice(e, &mut slice, Configuration::standard()).unwrap();
        assert_eq!(bytes_written, 1);
        slice[0]
    }

    assert_eq!(ser(MyEnum::Foo), 3);
    assert_eq!(ser(MyEnum::Bar), 5);
    assert_eq!(ser(MyEnum::Baz), 6);
}
```

Output

```
running 1 test
test test_my_enum ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 12 filtered out; finished in 0.00s
```

**Comment by mattfbacon** [comment]
As I'm using this library for a specification out of my control, where all the integers are fixed size, I'm using fixed integers in Bincode. However, many of the enums are specified as having a 1-byte representation.

**Comment by mattfbacon** [comment]
Also, my mistake about the values. It looks like Bincode does respect them. I'll edit the title.

**Comment by VictorKoenders** [comment]
Bincode doesn't aim to support other formats, I'm afraid this isn't the right library for what you're trying to do

**Comment by VictorKoenders** [comment]
You could always implement an `Encode` and `Decode` manually, which would happen to line up with the format you're trying to use. See the `target` folder for the auto-generated code that `bincode-derive` produces to get started.

**Comment by mattfbacon** [comment]
Is there a reason to not respect the repr tag?

**Comment by VictorKoenders** [comment]
The original format specified enum as `u32` and all the requests we've had to change this is to support encoding/decoding other formats that happened to be very close to bincode's. We're not interested in supporting other formats at this time because it'll pollute our codebase.

**Comment by VictorKoenders** [comment]
We just updated the README to reflect this, as this question has come up a lot: https://github.com/bincode-org/bincode#why-does-bincode-not-respect-repru8

**Comment by mattfbacon** [comment]
Oh, I see. Can you recommend a library meant for custom formats? Or do I have to write my own?

**Comment by VictorKoenders** [comment]
Maybe something like [nom](https://docs.rs/nom) would work for your case?

**Comment by mattfbacon** [comment]
I ended up writing my own. Your library's derive implementation helped a lot with that :)

Anyway, closing.
