### ISSUE TITLE
Consider using different encoding config for length/discriminants and other values.

### ISSUE THREAD

**Issue by ygf11** [bincode-org/bincode#476]
Hi, it seems `encoding` is a global config.
```rust
enum Foo {
    A(u16),
    B(u32),
}

let vec = vec![Foo::A(0u16)];
let config = Configuration::standard().with_variable_int_encoding();
bincode::encode_into_std_write(vec, &mut writer, config);
```

for `Vec<Foo>`, `varint encoding` config will take effect:

-  vec length and enum discriminants
-  other values, such as inner `u16` in `Foo::A`

In some scenario, we know length/discriminants is in small range, so it is better to use `varint` encoding,
while the range of other values is not clear, so it is better to use `fixint`.

**Comment by VictorKoenders** [comment]
I don't think we're interested in adding this as it will add a lot of complexity. Are you running into a real world issue where the possible padding of 1 byte of the varint encoding outweighs the benefit of very frequently being able to store the integer in a smaller format?

Keep in mind that `varint` will be smaller than `fixint` when `val < INT::MAX / 2`, which seems to happen a lot in real world applications.

There is a workaround mentioned https://github.com/bincode-org/bincode/issues/415#issuecomment-950203570 that might work for you.

**Comment by ygf11** [comment]
Thanks, got it.
