### ISSUE TITLE
Invoking the options struct adds additional bytes to resulting output

### ISSUE THREAD

**Issue by samuwen** [bincode-org/bincode#508]
Code:
```
let ie = IndexEntry {
    ctime: 1645850906,
    ctime_nsec: 704990044,
    mtime: 1645498338,
    mtime_nsec: 535928285,
};
let b1 = bincode::options()
    .serialize(&ie)
    .expect("failed to serialize");
let b2 = bincode::serialize(&ie).expect("failed to serialize");
assert_eq!(b1, b2);
```

Output:
```
left:   `[252, 26, 177, 25, 98, 252, 92, 75, 5, 42, 252, 226, 79, 20, 98, 252, 221, 157, 241, 31]`,
right: `[26, 177, 25, 98, 92, 75, 5, 42, 226, 79, 20, 98, 221, 157, 241, 31]`'
```

As you can see, 4 bytes of 252 are added to b1's output as it uses the options function.

**Comment by VictorKoenders** [comment]
`bincode::serialize` uses ` DefaultOptions::new().with_fixint_encoding()` [source](https://github.com/bincode-org/bincode/blob/v1.x/src/lib.rs#L110-L113).

`bincode::options()` is `varint` by default [docs](https://docs.rs/bincode/latest/bincode/fn.options.html), which has a smaller binary output by default.

More information on varint can be found [here](https://docs.rs/bincode/latest/bincode/config/struct.VarintEncoding.html)
