### ISSUE TITLE
Better limit estimation in 2.x

### ISSUE THREAD

**Issue by ghost** [bincode-org/bincode#512]
Limit estimation for enums in particular can grossly underestimate the actual allocated size.

in
```rust
enum Foo {
    Bar(u8),
    Baz(SomeLargeType),
}
```
bincode could end up thinking only 5 bytes were claimed (4 for the discriminant, 1 for the u8), but enums take up the size of their largest variant.

Possibilites:
- Overclaim enums for their full size
  - downside of potentially returning limit errors before actual allocated memory reaches the limit
- Only claim for allocated types
  - stack allocated types will _always_ blow the stack if they are too large regardless of input. Its heap allocation that can cause issues.

**Comment by Evrey** [comment]
This is also important to state in the spec: https://github.com/bincode-org/bincode/issues/517

As it is now, the spec *implies* only allocating just enough bytes for the currently set variant.
