### ISSUE TITLE
Derive decode for struct with fields with different endianness

### ISSUE THREAD

**Issue by wangbj** [bincode-org/bincode#514]
For below struct:

```rust
#[drive(Decode)]
struct Foo {
    identifier: u32,     // big endian, fixed size.
    flags: u32,          // native endian, fixed size.
}
```

How could this work with `bincode-2`? Asking this question for serveral reasons:

1)  There's a `Config` argument in`decode_from_reader`, it can be configured to either big endian or little endian, but neither would work for above struct?
2) Would it make sense to add endianness annotations for some field, like `binread` crate?
3) With a combination of both 1) and 2), when there're enough annotations to tell how to deserialize the data, why a `Config` argument is needed at all (at least wrt endianness)?

**Comment by ghost** [comment]
It sounds like you're trying to use bincode to interface with a foreign format. Is that correct? Bincode does not support compatibility with formats other than bincode. The endianness config was designed purely to improve speed on systems with different endianness.
