### ISSUE TITLE
Provide a public API to manually encode/decode inner types.

### ISSUE THREAD

**Issue by whizsid** [bincode-org/bincode#520]
I want to `Encode` and `Decode` an external type which contains vectors and options. So currently I am doing in this way.

```rust
# External Crate
pub struct A {
    x: u8,
    y: u8
}

pub struct B {
    coords: Option<A>
}

# My Crate
pub struct C (B);

match self.0 {
   Some(b) => {
       bincode::Encode::encode(&1u8, encoder)?;
       bincode::Encode::encode(&b.x, encoder)?;
       bincode::Encode::encode(&b.y, encoder)?;
   }
   None=> {
       bincode::Encode::encode(&0u8, encoder)?;
   }
}
```
I discovered it from internal source files. If you can add several methods like `encode_option`, `decode_option`, `encode_vec`, `decode_vec` then it will be easy for new comers.

**Comment by VictorKoenders** [comment]
Would using the serde compatibility structs and functions work for your case? More information here: https://docs.rs/bincode/2.0.0-rc.1/bincode/serde/index.html

**Comment by whizsid** [comment]
@VictorKoenders Unfortunately I can not use serde in this specific use case. Because I am using the serde to serialize same data structures in a human readable format. 

### Example:-

My enum:-
```
pub enum Unit {Px, Pt,Rem, Em, Percent}
```
Serde output:-
```
"px","pt","rem","em","%"
```
bincode output:-
```
0u8,1u8, 2u8,3u8,4u8
```

I am using bincode to store states of my data structure (To perform Undo, Redo operations). But serde to serialize as XML and allow download to users.

However I am closing this issue. Because I manually implemented Encode and Decode to all of my types. And I think this is a rare usecase and newcomers can use serde feature.
