### ISSUE TITLE
Change `UnexpectedEnd` to include the expected size

### ISSUE THREAD

**Issue by aviramha** [bincode-org/bincode#521]
Right now the enum variant of ErrorKind `UnexpectedEnd` is void. I suggest changing it to `UnexpectedEnd(usize)` so the caller will be able to know how much data it is missing for success.

This will allow development of stream protocols to be more efficient by reserving buffers & calling the decode only when data is complete.

More specifically, I'm now developing a `actix-codec` `Encoder`/`Decoder` and I'd wish to reserve the additional missing data before returning.

Thoughts?

**Comment by VictorKoenders** [comment]
```rs
#[derive(Decode)]
struct Foo {
    a: u64, 
    b: u64
}
```
Because bincode does not have a look ahead system, if you feed this struct only 1 byte, it would report a `UnexpectedEnd(7)` as `u64` needs 8 bytes. Not the 15 bytes it actually needs. Would this be good enough for your case?

**Comment by aviramha** [comment]
Yes.
