### ISSUE TITLE
Error types do not implement `Error::source`

### ISSUE THREAD

**Issue by Aeledfyr** [bincode-org/bincode#528]
Both the `ErrorKind` type in bincode `1.3.3` and the `EncodeError`/`DecodeError` types in bincode `2.0.0-rc.1` do not implement the `source` method in `std::error::Error`, which allows for automatic introspection of error causes.

Implementing it in `1.3.3` should be trivial, as it should be possible to reusing the implementation of the deprecated `cause` method (which `1.3.3` implements).

I've noticed that bincode `1.0` appears to have a MSRV below the version in which `source` was added.  Does this prevent the library from implementing it in any form, or can conditional compilation be used to implement it if the compiler version supports it?

**Comment by VictorKoenders** [comment]
I agree this is a good idea. I've implemented this for bincode 2 in #530.

Bincode 1 is in maintenance mode, we don't plan to add new features in the foreseeable future.
