### ISSUE TITLE
Encode/Decode implementations are stored in `target` directory

### ISSUE THREAD

**Issue by mahkoh** [bincode-org/bincode#531]
I've been using bincode 2.0.0-rc.1 and I've noticed files using the pattern `AccelProfile_Decode.rs` being generated directly in the `target` directory. Would it be possible to move these files to a bincode-specific directory?

**Comment by VictorKoenders** [comment]
What directory are you thinking of? Maybe generate `target/bincode_gen` and put the files in there?

**Comment by dtolnay** [comment]
This was reopened as #594 and resolved by #600.
