### ISSUE TITLE
Example code in the README does not compile

### ISSUE THREAD

**Issue by Dentrax** [bincode-org/bincode#544]
I was trying the [Example](https://github.com/bincode-org/bincode#example) in the README. And I'm getting the following errors:

* unresolved imports `bincode::Decode`, `bincode::Encode`
* cannot find function `standard` in module `config`
* cannot find function `decode_from_slice` in crate `bincode`

I added `bincode = "1.3.3"` in `[dependencies]` section.

Any ideas? 🤔

**Comment by Dentrax** [comment]
Tested on latest version `bincode = "2.0.0-rc.1"` is worked! Maybe we should update the README. 🤞

**Comment by VictorKoenders** [comment]
The README seems up to date for `2.0.0-rc.1`, and I don't see a mention of `1.3.3` anywhere. What do you think should be updated in the README?

**Comment by Dentrax** [comment]
Oh, i think i saw `1.3.3` version on [crates](https://crates.io/crates/bincode/) and jump directly into GitHub page and copied the example section in the README. So I thought it's `1.3.3`. Closing.

**Comment by havok4u** [comment]
I see this issue in 1.3.3 and yes using the rc release fixes it, but when will it make it into stable release i.e. 1.3.4?  Item was closed may of 2022.

**Comment by VictorKoenders** [comment]
Tracking issue for the 2.0 release: https://github.com/bincode-org/bincode/issues/674
