### ISSUE TITLE
Does bincode respect `#[repr(align(4))]`?

### ISSUE THREAD

**Issue by Dentrax** [bincode-org/bincode#545]
I have the following struct:

```rust
#[derive(Encode, Decode, PartialEq, Debug)]
#[repr(align(4))]
pub struct Packet {
 foo: bool,
 bar: u32,
 baz: f32,
 qux: u16
}
```

I'm reading from a socket and for each 4th index represents a field in the struct:
```rust
let mut buf = vec![0; MAX_DATAGRAM_SIZE];
let config = config::standard();
let (decoded, len): (Packet, usize) = bincode::decode_from_slice(&buf[..], config).unwrap();
```

The following above code works but prints random values and I'm not sure if `bincode` reads bytes at index 4-by-4 and respects `#[repr(align(4))]`. Simply I want to achieve following scenario, is it possible with bincode? Thanks.

```
foo: buf[0..4]
bar: buf[4..8]
baz: buf[8..12]
...
```

**Comment by Dentrax** [comment]
Created a minimal reproducible:

```rust
#[cfg(test)]
mod tests {
    use std::{mem, slice};
    use bincode::config;
    use crate::{decoder, Packet};

    #[test]
    fn decode() {
        // represents a UDP packet
        const BUFFER: &[u8] = &[
            0x01, 0x02, 0x00, 0x00, // bool - foo
            0x05, 0x00, 0x00, 0x01, // u32  - bar
            0x00, 0x00, 0x00, 0x00, // f32  - baz
            0x00, 0x00, 0x00, 0x00, // u16  - qux
        ];

        let config = config::standard();
        let packet: Packet = decoder::decode(config, BUFFER);

        assert_eq!(packet.foo, true);
        assert_eq!(packet.bar, 5);
    }
}
```

Since I use `#[repr(align(4))]` in my `Packet` struct, I expect `assert_eq!(packet.bar, 5);` should return `true` but instead, `bar` is `2`. (Notice second u8, which is 0x02).

What I want from bincode is to read my buffer 4-by-4 bytes. But it reads single `u8` unit. 🤔

**Comment by VictorKoenders** [comment]
Bincode does not respect `align`. We have an explanation why we don't support `#[repr(u8)]` in the [readme](https://github.com/bincode-org/bincode#why-does-bincode-not-respect-repru8), and I think that explanation applies to this case as well

The short answer is that Bincode is only interested in supporting its own protocol.
