### ISSUE TITLE
Extend documentation for decode_from_slice and encode_into_std_write

### ISSUE THREAD

**Issue by hellow554** [bincode-org/bincode#546]
[`decode_from_slice`](https://docs.rs/bincode/2.0.0-rc.1/bincode/fn.decode_from_slice.html) does not say what the `usize` is for.

[`encode_into_std_write`](https://docs.rs/bincode/2.0.0-rc.1/bincode/fn.encode_into_std_write.html) does not say what the `usize` is for.

**Comment by ghost** [comment]
Should be fixed by #577
