### ISSUE TITLE
glam crate is giving corrupt number when serialized via serde

### ISSUE THREAD

**Issue by cybersoulK** [bincode-org/bincode#547]
bincode 1.3.3 is fine
bincode2 (forked) is fine

<img width="326" alt="image" src="https://user-images.githubusercontent.com/102260392/171771606-1355cd99-f030-44c1-8ae3-588f627f3b48.png">

first value is original, 
second is bind code 1.3.3 or bincode2,
third is bincode v.2

the third value can output NaN sometimes.

I tried different settings in the config. and I tried to serialize my own struct of floats, and it works.
no idea why it doesn't work for glam::Vec3

serde is latest version, tried with multiple versions.
serde has field default-features = false

serde::encode_to_vec
serde::decode_from_slice

are side to side and there are no other factors involved

**Comment by VictorKoenders** [comment]
Make sure you use the right config for both encoding and decoding. There is a [migration guide](https://docs.rs/bincode/2.0.0-rc.1/bincode/migration_guide/index.html) that explains everything.

If this doesn't solve your issue please provide a minimal reproduction example.

**Comment by cybersoulK** [comment]
minimal reproduction
https://github.com/cybersoulK/test_bincode

output: Instance { position: Vec3(2.0, 2.0, 2.0) }, Instance { position: Vec3(4e-45, 9e-44, 9e-44) }
machine: Mac m1 pro
