### ISSUE TITLE
`BorrowDecode` is unimplemented for tuples (2.0.0-rc.1)

### ISSUE THREAD

**Issue by maciejhirsz** [bincode-org/bincode#550]
Trying to upgrade from 1.0 to 2.0 I'm running into issues mostly around the default trait being `Decode` rather than `BorrowDecode`, which is reverse of what serde is doing.

Specifically the generic tuple impls are done only for tuples that implement `Decode`, which means that if one, or even all members of a tuple implement `BorrowDecode`, it's not possible to use `BorrowDecode` on said tuple. This was never an issue with serde.

**Comment by VictorKoenders** [comment]
The current `trunk` version in this repo has had some massive changes in that area. Could you try again against `trunk` and see if this issue is still valid?

**Comment by maciejhirsz** [comment]
@VictorKoenders yep, it's fixed on trunk, cheers!
