### ISSUE TITLE
`no_std` support with `serde` feature

### ISSUE THREAD

**Issue by tsoutsman** [bincode-org/bincode#556]
Hi, I've come across (what I think is) a bug with `no_std` support in the `2.0.0-rc.1` version.

A new library with the following files:
`Cargo.toml`:
```toml
# package keys ...

[dependencies.bincode]
version = "2.0.0-rc.1"
default-features = false
features = ["serde"]
```
and `lib.rs`:
```rust
#![no_std]

use bincode;

#[panic_handler]
fn panic_handler(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
```
fails to compile with the error:
```
error[E0152]: found duplicate lang item `panic_impl`
 --> src/lib.rs:6:1
  |
6 | fn panic_handler(_: &core::panic::PanicInfo) -> ! {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the lang item is first defined in crate `std` (which `bincode` depends on)
  = note: first definition in `std` loaded from /home/klim/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-91db243dd05c003b.rlib
  = note: second definition in the local crate (`temp5`)
```
Stating that `bincode` depends on `std`.

However, the following `lib.rs`:
```rust
#![no_std]

use bincode;
```
Still compiles, implying that `bincode` does not depend on `std` (as far as my understanding of `no_std` goes).

Removing the `serde` feature removes the errors.

This seems to be related to [this issue](https://github.com/rust-lang/cargo/issues/7915), but adding `resolver = "2"` to `Cargo.toml` doesn't fix it.

**Comment by ghost** [comment]
This could be due to the fact that `rc.1` only allowed serde with `std` enabled. This has been fixed on trunk with the stabilization of weak dependencies. Can you see if depending on trunk fixes your issue?

**Comment by VictorKoenders** [comment]
We had some difficulty importing `serde` and `no_std`. As Zoey said this should be fixed on trunk with weak dependencies.

If you want to use rc.1, you can try the `serde_no_std` feature: https://github.com/bincode-org/bincode/blob/v2.0.0-rc.1/Cargo.toml#L33-L40

**Comment by tsoutsman** [comment]
Yep, it works both with `serde_no_std` and when using trunk as a dependency. Thanks!

**Comment by tsoutsman** [comment]
Oops, now I can't access the `serde` module when using the `serde_alloc` feature:
```
error[E0432]: unresolved import `bincode::serde`
 --> src/lib.rs:3:5
  |
3 | use bincode::serde;
  |     ^^^^^^^^^^^^^^ no `serde` in the root

For more information about this error, try `rustc --explain E0432`.
```
But this seems to be fixed on trunk, so I'll leave the issue closed.
