### ISSUE TITLE
Simple vector serialization question

### ISSUE THREAD

**Issue by dnat112** [bincode-org/bincode#558]
I have code that resembles the following:
```
    let mut v: Vec<i8> = Vec::with_capacity(7);
    v.push(1); v.push(2); v.push(3); v.push(4); v.push(5); v.push(6); v.push(7);
    println!("serialized_size(v) = {:?}", bincode::serialized_size(&v));
```

I would expect that the serialized_size would be (7 vector elements * 1 byte / element) = 7 bytes. However, the actual result is:

> serialized_size(v) = Ok(15)

Is this the expected behavior? Where does the 15 come from?

Thank you

**Comment by ghost** [comment]
It comes from the 8-byte vector length prefix since `usize` is serialized as a `u64` in bincode 1.x with the default configuration. This can be shortened by using the varint configuration.
