### ISSUE TITLE
Derive macros break with where clauses

### ISSUE THREAD

**Issue by SabrinaJewson** [bincode-org/bincode#561]
Test case:

```rs
#[derive(bincode::Encode)]
struct Test<T>
where
    T: Clone,
{
    a: T,
}
```

Output:

```
error: expected one of `{`, lifetime, or type, found `,`
 --> src/main.rs:3:10
  |
3 | #[derive(bincode::Encode)]
  |          ^^^^^^^^^^^^^^^ expected one of `{`, lifetime, or type
  |
  = note: this error originates in the derive macro `bincode::Encode` (in Nightly builds, run with -Z macro-backtrace for more info)

error: proc-macro derive produced unparseable tokens
 --> src/main.rs:3:10
  |
3 | #[derive(bincode::Encode)]
  |          ^^^^^^^^^^^^^^^
```

**Comment by VictorKoenders** [comment]
There is an attribute you can use called `bounds`, I only just noticed we've not documented this.

There is an example in [tests/issues/issue_431.rs](https://github.com/bincode-org/bincode/blob/trunk/tests/issues/issue_431.rs) that uses `borrow_decode_bounds`. There are these 4 attributes:
- `bounds`, used by all 3 derives
- `decode_bounds`, used by `#[derive(Decode)]`
- `borrow_decode_bounds`, used by `#[derive(BorrowDecode)]`
- `encode_bounds`, used by `#[derive(Encode)]`

You can check `target/test_Encode.rs` to see what bounds would be needed.

This is assuming either virtue or bincode-derive doesn't do something weird

**Comment by SabrinaJewson** [comment]
Thanks — the following does compile:

```rs
#[derive(bincode::Encode)]
#[bincode(encode_bounds = "T: bincode::Encode + Clone")]
struct Test<T>
where
    T: Clone,
{
    a: T,
}
```

I still think it would be nice for bincode to just automatically support where bounds, but if it must be unsupported could the error message be improved?

**Comment by purpleposeidon** [comment]
It appears it does attempt to support automatic bounds.

**Comment by dtolnay** [comment]
Bincode is still generating syntactically invalid code in this situation. That's a bug independent of whether `encode_bounds` exists.
