### ISSUE TITLE
proposal: Add variant encode for array length

### ISSUE THREAD

**Issue by Xuanwo** [bincode-org/bincode#564]
## Background

`Collections` said: The length value is based on your `IntEncoding`.

But in fact, array length only supports `write_fixed_array_length` and `skip_fixed_array_length`.

```rust
let arr: [u8; 5] = [10, 20, 30, 40, 50];
let encoded = bincode::encode_to_vec(arr, bincode::config::legacy()).unwrap();
assert_eq!(encoded.as_slice(), &[
    5, 0, 0, 0, 0, 0, 0, 0, // The length, as a u64
    10, 20, 30, 40, 50, // the bytes
]);

let encoded = bincode::encode_to_vec(arr, bincode::config::legacy().skip_fixed_array_length()).unwrap();
assert_eq!(encoded.as_slice(), &[
    // no length
    10, 20, 30, 40, 50, // the bytes
]);
```

## Proposal

We can support variant encodes for array length, which can make our array smaller, especially for arrays smaller than 256 (The cases happened in [databend](https://github.com/datafuselabs/databend/) which will operate many small slices)

```rust
let arr: [u8; 5] = [10, 20, 30, 40, 50];
let encoded = bincode::encode_to_vec(arr, bincode::config::legacy().write_variant_array_length()).unwrap();
assert_eq!(encoded.as_slice(), &[
    5, // The length, as a single byte
    10, 20, 30, 40, 50, // the bytes
]);
```

## Reference

Add a new const bool in trait `InternalArrayLengthConfig`:

```rust
pub trait InternalArrayLengthConfig {
    const SKIP_FIXED_ARRAY_LENGTH: bool;
    const WIRTE_VARIANT_ARRAY_LENGTH: bool;
}
```

Implement a config struct:

```rust
#[doc(hidden)]
#[derive(Copy, Clone)]
pub struct WriteVariantArrayLength {}

impl InternalArrayLengthConfig for WriteVariantArrayLength {
    const SKIP_FIXED_ARRAY_LENGTH: bool = false;
    const WIRTE_VARIANT_ARRAY_LENGTH: bool = true;
}
```

## Alternative

If API break is allowed, we can make `InternalArrayLengthConfig` refer to an enum:

```rust
enum InternalArrayLengthOption {
    SKIP_FIXED_ARRAY_LENGTH,
    WIRTE_VARIANT_ARRAY_LENGTH,
    WIRTE_FIXED_ARRAY_LENGTH,
}

pub trait InternalArrayLengthConfig {
    const SKIP_FIXED_ARRAY_LENGTH: InternalArrayLengthOption;
}
```

## Other contexts

We have implemented the same feature on bincode v1 on our fork: https://github.com/datafuse-extras/bincode

**Comment by Xuanwo** [comment]
Cc @VictorKoenders for reviewing.
Cc @sundy-li @ygf11 for acknowledgment.

**Comment by VictorKoenders** [comment]
It sounds to me that this is a strict subset of `.with_variable_int_encoding()`, am I missing something? Does `.with_variable_int_encoding()` not do what you want?

**Comment by Xuanwo** [comment]
> It sounds to me that this is a strict subset of `.with_variable_int_encoding()`, am I missing something? Does `.with_variable_int_encoding()` not do what you want?

With the default config (which `VarintEncoding` selected by default), array length will be written as fixed length (u64):

```rust
let arr: [u8; 5] = [10, 20, 30, 40, 50];
let encoded = bincode::encode_to_vec(arr, bincode::config::legacy()).unwrap();
assert_eq!(encoded.as_slice(), &[
    5, 0, 0, 0, 0, 0, 0, 0, // The length, as a u64
    10, 20, 30, 40, 50, // the bytes
]);
```

**Comment by VictorKoenders** [comment]
`legacy` uses fixed int encoding, try switching to `config::standard()` or enabling `.with_variable_int_encoding()`

https://docs.rs/bincode/2.0.0-rc.1/bincode/config/fn.legacy.html: `Fixed int length encoding`

https://docs.rs/bincode/2.0.0-rc.1/bincode/config/fn.standard.html: `Variable int encoding`

**Comment by Xuanwo** [comment]
> `legacy` uses fixed int encoding, try switching to `config::standard()` or enabling `.with_variable_int_encoding()`

Thank you very much for pointing out! I must miss this part.

@sundy-li @ygf11, maybe we can migrate from `datafuse-extras/bincode` to bincode directly?

**Comment by Xuanwo** [comment]
> `legacy` uses fixed int encoding, try switching to `config::standard()` or enabling `.with_variable_int_encoding()`

I'm a bit confused.

```rust
/// Decodes the length of any slice, container, etc from the decoder
#[inline]
pub(crate) fn decode_slice_len<D: Decoder>(decoder: &mut D) -> Result<usize, DecodeError> {
    let v = u64::decode(decoder)?;

    v.try_into().map_err(|_| DecodeError::OutsideUsizeRange(v))
}
```

We always try to decode `u64` as the slice's length. How could they be variable int encoding?

**Comment by VictorKoenders** [comment]
The `Decoder` has a reference to your config, which contains the `INT_ENCODING` that is configured: https://github.com/bincode-org/bincode/blob/trunk/src/de/impls.rs#L119

**Comment by VictorKoenders** [comment]
For reference you can look at this test, which decode and encodes a slice with variable int encoding: https://github.com/bincode-org/bincode/blob/trunk/tests/basic_types.rs#L133-L144

Note how it prepends the slice with `7`, and not `0, 0, 0, 0, 0, 0, 0, 7`

**Comment by Xuanwo** [comment]
Thanks a lot!

**Comment by ygf11** [comment]
> maybe we can migrate from datafuse-extras/bincode to bincode directly?

`varint` will encode both length and data to `varint`. for example:
```rust
    let mut buffer = [0u8; 32];
    let input: &[u16] = &[1, 2, 3, 4, 253];
    let config = bincode::config::standard();
    let bytes_written = bincode::encode_into_slice(input, &mut buffer, config).unwrap();
    assert_eq!(bytes_written, 8);
    assert_eq!(&buffer[..8], &[5, 1, 2, 3, 4, 251, 253, 0]);
```

`bincode` are mainly used to `serialize/deserialize` aggregate state in databend, as @@sundy-li suggests:

- Enum tag and vec/slice length, are better coded with `varint`.
- Other data are better with `fixedint`, since the are not clear in our scene.

I asked @VictorKoenders before in #476, and he give us a way friendly, like #415 does.

So I think we can try to use v2 with `varint` first, if the performance does not match our expect, we can also try to use the wrapper way.

**Comment by Xuanwo** [comment]
I will give v2 a try!

**Comment by Xuanwo** [comment]
Databend has migrated to `bincode-org/bincode`.

Thanks for the help from @VictorKoenders @ygf11!
