### ISSUE TITLE
prelude, or something

### ISSUE THREAD

**Issue by purpleposeidon** [bincode-org/bincode#568]
```rust
use bincode::{Encode, Decode};
use bincode::enc::Encoder;
use bincode::de::Decoder;
use bincode::error::{EncodeError, DecodeError};
```
All a bit much for what could be a 1-liner.

**Comment by VictorKoenders** [comment]
We'd expect most users to only need `use bincode::{Encode, Decode};`. The other types are only needed for implementing a custom decode/encode. Is this assumption correct?

We could make a `pub mod impl_prelude` or something

**Comment by purpleposeidon** [comment]
Yes, that would be lovely.

**Comment by dtolnay** [comment]
A contributing factor here is that the current way that bincode has organized items into modules is not well aligned with what items programmers will most often be using together. I don't feel that a prelude is the solution; I would not use one if one existed. Instead I'd prefer the module hierarchy to be revamped a bit.

For the same set of imports that @purpleposeidon wrote as 4 lines above, I would expect to write:

```rust
use bincode::enc::{Encode, Encoder, EncodeError};
use bincode::de::{Decode, Decoder, DecodeError};
```

which seems reasonable to me and does not begin to necessitate a prelude in my opinion.
