### ISSUE TITLE
Exceed max variant index 

### ISSUE THREAD

**Issue by ScottLinnn** [bincode-org/bincode#569]
I have an enum containing three variants and I added a new variant in it, but when I inputted the bytes of the new variant and tried to deserialize it into the enum through `bincode::deserialize(bytes_of_new_variant)`, it gave me this message: 

`invalid value: integer 3, expected variant index 0 <= i < 3
`

I tried many ways to debug but still couldn't figure this out. Can I get any help on this? Thanks!

**Comment by nmccarty** [comment]
Can you provide a minimal reproducible example, i.e. the definition of the enum and the code you are using for testing?

That will make it much easier to figure out what's going wrong

**Comment by ScottLinnn** [comment]
The definition is like this:   
```
pub enum Kind {
    A,
    B,
    C,
    D, // The newly added variant
}
```
And the code is like:
`let kind:Kind = bincode::deserialize(bytes)?; // bytes is &Bytes type`    
Thanks!

**Comment by VictorKoenders** [comment]
```rs
#[derive(serde::Serialize, serde::Deserialize, Debug)]
pub enum Kind {
    A,
    B,
    C,
    D, // The newly added variant
}

#[test]
fn test() {
    let kind: Kind = bincode::DefaultOptions::default()
        .with_varint_encoding()
        .deserialize(&[3])
        .unwrap();
    println!("{:?}", kind);
}
```
Works for me

**Comment by ScottLinnn** [comment]
Thank you! After quite some time I found it's some docker issues that make my code deserializing enum not updated(only has three variants in enum)while the code serializing it has been updated. Sorry for this!
