### ISSUE TITLE
new v2 release candidate to include support for `Box`ed/`Rc`ed/`Arc`ed dynamically-sized types?

### ISSUE THREAD

**Issue by ruifengx** [bincode-org/bincode#571]
I believe this part is already implemented currently in this repo, but not yet released to `crates.io`. Personally, I feel more comfortable having `crates.io` dependencies than `git` dependencies. I understand that a stable 2.0 version is probably not ready yet, but would you mind having another release candidate `2.0.0-rc.2`? Thanks.

**Comment by VictorKoenders** [comment]
I've just updated the 2.0.0-rc.2 milestone which tracks that release: https://github.com/bincode-org/bincode/milestone/6

we've been busy the last couple of months but if you have time feel free to pick up any of those issues

**Comment by ruifengx** [comment]
Thanks for your timely reply! I just had a quick look at the four issues listed in the milestone. It seems to me (correct me if I am wrong) that only the `peek_read` one requires actual code changes, for which there is already a pending PR, and the three others involves only documentation changes. I am not particularly self-confident on writing documentations, but I can definitely give it a try anyway.
