### ISSUE TITLE
Should `CString`s be encoded as Collections?

### ISSUE THREAD

**Issue by GreenYun** [bincode-org/bincode#579]
As of bincode-2.0.0-rc.1, `CString`s are converted to `&[u8]` and are encoded as Collections (with length and data, without the trailing zero).

I do not think this is the form of what `CString`s supposed to be encoded. We would like it to be translated in to zero-terminated strings, and decode those into `CStrings`.

**Comment by VictorKoenders** [comment]
Unfortunately we need to be compatible with bincode 1, and bincode 1 is compatible with serde, and serde has made the decision that CString should be encoded as bytes: https://github.com/serde-rs/serde/blob/master/serde/src/ser/impls.rs#L86-L95

What is your use case where you need a zero-terminated string?

**Comment by GreenYun** [comment]
I am working on implementing some network protocols that transfer zero-terminating strings and integers. I would like to use bin code for converting between octet streams and structs.

**Comment by VictorKoenders** [comment]
Unfortunately bincode does not support other formats than its own

**Comment by GreenYun** [comment]
Ok I will implement my `Encoder` and `Decoder` for zero-terminated strings.
