### ISSUE TITLE
Represent Option<NonZeroT> as T

### ISSUE THREAD

**Issue by nonnorm** [bincode-org/bincode#582]
In memory, an `Option<NonZeroT>` has the same size as a `T`. While I'm not sure exactly how Rust does this, I'm going to assume that it is by storing it in memory as a `T`, with the zero value being interpreted as `None`. Bincode could do the same thing, encoding an `Option<NonZeroT>` as a `T`. This would save space in the final encoding, which I know is not the goal of Bincode, but I think it would be good to follow Rust's example here. However, this would also allow an encoded `Option<NonZeroT>` to be decoded as a `T`, or vice versa, and I'm not sure if this would be a problem or not.

**Comment by VictorKoenders** [comment]
We can detect in bincode if type `T` cannot be encoded/decode as `0`, because `T` might implement a `Encode` that does use `0` for a different value. Consider:
```rs
pub enum Foo {
    Bar = 1, // trigger non-zero optimization
    Baz = 2,
}
impl Encode for Foo {
    fn encode<E: Encoder>(&self, encoder: &mut Encoder) -> Result<(), bincode::error::EncodeError> {
        ((self as usize) - 1).encode(encoder)
    }
}
```
Bincode would encode `Option::<Foo>::None` as `0` but `Option::<Foo>::Some(Foo::Bar)` as `0` as well.

**Comment by VictorKoenders** [comment]
Additionally we can't implement this optimization for `Option<NonZeroUsize>` because it'd conflict with the implementation for `Option<T> where T: Encode` because we implement `impl Encode for NonZeroUsize`.

Another one for the long list of "maybe if implementation specialization gets stabilized"
