### ISSUE TITLE
negative explicit variant discriminator not allowed in enums

### ISSUE THREAD

**Issue by trevyn** [bincode-org/bincode#592]
From https://github.com/bincode-org/bincode/issues/537#issuecomment-1114170682:

> `error: Invalid rust syntax, expected literal, got Some(Punct { ch: '-', spacing: Alone, span: #0 bytes(20762..20763) })`
> 
> ```rust
> #[derive(Encode, Decode)]
> pub enum TypeOfFile {
>     Unknown = -1,
> }
> ```

It appears that enum discriminators are encoded as `u32`, and changing this to `i32` will change the byte encoding of positive discriminators as well.

I've done some work on a patch for this if this is a desirable change.

**Comment by VictorKoenders** [comment]
It looks like serde encodes the variants as their index, not as the actual value:

```rs
#[derive(serde::Serialize)]
enum Foo {
    A = -1,
}

fn main() {
    println!("{:?}", bincode::serialize(&Foo::A))
}
```

Prints out `Ok([0, 0, 0, 0])`

Unfortunately we have to remain backwards compatible with bincode 1.3.3 so the change is that we should encode it as the variant index, not the value of the variant.

If you're willing to make this PR that would be appreciated!

**Comment by trevyn** [comment]
I was looking at `Encode`/`Decode`; so changing its encoding from the current is OK?

**Comment by VictorKoenders** [comment]
Yes, I believe the current implementation encodes enum variants as their values. They need to be encoded as their index

```rs
enum Foo {
    Bar = 5, // needs to be encoded as 0u32
}
```
