### ISSUE TITLE
Exposing config to implement custom Encode/Decode

### ISSUE THREAD

**Issue by Code0x2** [bincode-org/bincode#598]
I am trying to create custom Encode/Decode implementations for types in other crates that I'd like to use. However, I cant access the configuration as done on the impls.rs file of the encoder. How can I access the config (endianess, fixed/varint, etc) to write the data from the external type according to the config of the encoder/decoder?

**Comment by VictorKoenders** [comment]
Which config flags do you need access to?

We should be able to add functions to the [Config](https://docs.rs/bincode/2.0.0-rc.2/bincode/config/trait.Config.html) trait, which should mean that we're always forward compatible. Something like:

```patch
diff --git a/src/config.rs b/src/config.rs
index bb3129f..9ff29fd 100644
--- a/src/config.rs
+++ b/src/config.rs
@@ -191,6 +191,11 @@ impl<E, I, A, L> Configuration<E, I, A, L> {
     }
 }
 
+pub enum Endianness {
+    Big,
+    Little,
+}
+
 /// Indicates a type is valid for controlling the bincode configuration
 pub trait Config:
     InternalEndianConfig
@@ -200,16 +205,21 @@ pub trait Config:
     + Copy
     + Clone
 {
+    fn endianness(&self) -> Endianness;
 }
 
-impl<T> Config for T where
+impl<T> Config for T
+where
     T: InternalEndianConfig
         + InternalArrayLengthConfig
         + InternalIntEncodingConfig
         + InternalLimitConfig
         + Copy
-        + Clone
+        + Clone,
 {
+    fn endianness(&self) -> Endianness {
+        <T as InternalEndianConfig>::ENDIAN
+    }
 }
 
 /// Encodes all integer types in big endian.
@@ -217,7 +227,7 @@ impl<T> Config for T where
 pub struct BigEndian {}
 
 impl InternalEndianConfig for BigEndian {
-    const ENDIAN: Endian = Endian::Big;
+    const ENDIAN: Endianness = Endianness::Big;
 }
 
 /// Encodes all integer types in little endian.
@@ -225,7 +235,7 @@ impl InternalEndianConfig for BigEndian {
 pub struct LittleEndian {}
 
 impl InternalEndianConfig for LittleEndian {
-    const ENDIAN: Endian = Endian::Little;
+    const ENDIAN: Endianness = Endianness::Little;
 }
 
 /// Use fixed-size integer encoding.
@@ -275,20 +285,14 @@ impl<const N: usize> InternalLimitConfig for Limit<N> {
 }
 
 mod internal {
-    use super::Configuration;
+    use super::{Configuration, Endianness};
 
     pub trait InternalEndianConfig {
-        const ENDIAN: Endian;
+        const ENDIAN: Endianness;
     }
 
     impl<E: InternalEndianConfig, I, A, L> InternalEndianConfig for Configuration<E, I, A, L> {
-        const ENDIAN: Endian = E::ENDIAN;
-    }
-
-    #[derive(PartialEq, Eq)]
-    pub enum Endian {
-        Little,
-        Big,
+        const ENDIAN: Endianness = E::ENDIAN;
     }
 
     pub trait InternalIntEncodingConfig {
```
@ZoeyR what do you think?

**Comment by Code0x2** [comment]
> Which config flags do you need access to?
> 
> We should be able to add functions to the [Config](https://docs.rs/bincode/2.0.0-rc.2/bincode/config/trait.Config.html) trait, which should mean that we're always forward compatible. Something like:
> 
> ```diff
> diff --git a/src/config.rs b/src/config.rs
> index bb3129f..9ff29fd 100644
> --- a/src/config.rs
> +++ b/src/config.rs
> @@ -191,6 +191,11 @@ impl<E, I, A, L> Configuration<E, I, A, L> {
>      }
>  }
>  
> +pub enum Endianness {
> +    Big,
> +    Little,
> +}
> +
>  /// Indicates a type is valid for controlling the bincode configuration
>  pub trait Config:
>      InternalEndianConfig
> @@ -200,16 +205,21 @@ pub trait Config:
>      + Copy
>      + Clone
>  {
> +    fn endianness(&self) -> Endianness;
>  }
>  
> -impl<T> Config for T where
> +impl<T> Config for T
> +where
>      T: InternalEndianConfig
>          + InternalArrayLengthConfig
>          + InternalIntEncodingConfig
>          + InternalLimitConfig
>          + Copy
> -        + Clone
> +        + Clone,
>  {
> +    fn endianness(&self) -> Endianness {
> +        <T as InternalEndianConfig>::ENDIAN
> +    }
>  }
>  
>  /// Encodes all integer types in big endian.
> @@ -217,7 +227,7 @@ impl<T> Config for T where
>  pub struct BigEndian {}
>  
>  impl InternalEndianConfig for BigEndian {
> -    const ENDIAN: Endian = Endian::Big;
> +    const ENDIAN: Endianness = Endianness::Big;
>  }
>  
>  /// Encodes all integer types in little endian.
> @@ -225,7 +235,7 @@ impl InternalEndianConfig for BigEndian {
>  pub struct LittleEndian {}
>  
>  impl InternalEndianConfig for LittleEndian {
> -    const ENDIAN: Endian = Endian::Little;
> +    const ENDIAN: Endianness = Endianness::Little;
>  }
>  
>  /// Use fixed-size integer encoding.
> @@ -275,20 +285,14 @@ impl<const N: usize> InternalLimitConfig for Limit<N> {
>  }
>  
>  mod internal {
> -    use super::Configuration;
> +    use super::{Configuration, Endianness};
>  
>      pub trait InternalEndianConfig {
> -        const ENDIAN: Endian;
> +        const ENDIAN: Endianness;
>      }
>  
>      impl<E: InternalEndianConfig, I, A, L> InternalEndianConfig for Configuration<E, I, A, L> {
> -        const ENDIAN: Endian = E::ENDIAN;
> -    }
> -
> -    #[derive(PartialEq, Eq)]
> -    pub enum Endian {
> -        Little,
> -        Big,
> +        const ENDIAN: Endianness = E::ENDIAN;
>      }
>  
>      pub trait InternalIntEncodingConfig {
> ```
> 
> @ZoeyR what do you think?

The endianness and fixed/variable length encoding options should be all

**Comment by ghost** [comment]
Why do you need these config items yourself? The design of `Config` assumed that any custom implementations of `Encode`/`Decode` would eventually encode primitive types, which already respect the `Config`. Can you provide an example of what you want to encode?

**Comment by Code0x2** [comment]
> Why do you need these config items yourself? The design of `Config` assumed that any custom implementations of `Encode`/`Decode` would eventually encode primitive types, which already respect the `Config`. Can you provide an example of what you want to encode?

https://docs.rs/ethers-core/latest/ethers_core/types/struct.U256.html 
I'm trying to encode a uint256 type, which supports directly converting into little or big endian

**Comment by shahn** [comment]
I've been working on a patch to teach `async-bincode` to directly use a bincode configuration, and for that I need access to the configured limit. This is required because the buffer that `async-bincode` reads into needs to respect the same limit. The only way I can see to do this with a nice API is to be able to pass a `Config` and then read the limit from it.

**Comment by VictorKoenders** [comment]
I think it's fine to add helper functions to return certain config values, maybe with a big message that we can change the config values (but honestly I don't expect we will)

Something like

```rs
    const fn endianness(&self) -> Endianness {
        <T as InternalEndianConfig>::ENDIAN
    }
    const fn int_encoding(&self) -> IntEncoding {
        <T as InternalIntEncodingConfig>::INT_ENCODING
    }
```

Maybe we should add `#[non_exhaustive]` to `Endianness` and `IntEncoding`  as well

**Comment by shahn** [comment]
Should I try and provide a patch?
