### ISSUE TITLE
Derive macros fail with new "explicit discriminants on enums with fields"

### ISSUE THREAD

**Issue by timwie** [bincode-org/bincode#606]
Rust 1.66 was just released, along with [Explicit discriminants on enums with fields](https://blog.rust-lang.org/2022/12/15/Rust-1.66.0.html#explicit-discriminants-on-enums-with-fields). The given example does not compile when adding bincode (2.0.0-rc.2) derive macros to the enum:

```
$ cargo -V
# cargo 1.66.0 (d65d197ad 2022-11-15)
```

```
#[derive(Decode, Encode)]
#[repr(u8)]
enum Foo {
    A(u8),
    B(i8),
    C(bool) = 42,
}

# error: Invalid rust syntax, expected ident, got Some(Punct { ch: '=', spacing: Alone, span: #0 bytes(334..335) })
```

**Comment by VictorKoenders** [comment]
Step 1 would be to implement this in virtue: [issue](https://github.com/bincode-org/virtue/issues/34)

After that we should see how serde implements this. With normal discriminants serde does not actually respect the value. e.g.

```rs
enum Foo {
    A = 5,
    B = 3,
}
```
Will still be encoded as `0` and `1` (See #592 for the reason why). I suspect this new syntax will also not actually respect the values, but instead use the index.
