### ISSUE TITLE
Question: Is bincode support no_std

### ISSUE THREAD

**Issue by yaoxin-jing** [bincode-org/bincode#607]
Hey, I want to use this crate in no_std.  Does it already support it?   

There is no doc on how to set it up in no_std env. So how can I set it up? Many thanks

@badboy @nelsonjchen @mbrubeck @antrik @jdm

**Comment by nelsonjchen** [comment]
Don't mention random people you buffoon.

**Comment by adamreichold** [comment]
There is also a similar codec that explicitly targets no_std: https://github.com/jamesmunns/postcard

**Comment by nelsonjchen** [comment]
Some of us haven't touched this project in <looks it up> 6 years or are involved in any meaningful capacities. Please don't spam notifications like that. Mass mentions like that blows past our notification settings and can annoy us.

**Comment by VictorKoenders** [comment]
Bincode 1.3.3 does not support `#![no_std]`

Bincode 2.0.0-rc does support `#![no_std]` but is not properly released yet
