### ISSUE TITLE
Serialization in Python

### ISSUE THREAD

**Issue by mikeylinton** [bincode-org/bincode#610]
Hi,

I'm waniting to deserializes the following array of bytes using bincode in Python.

```
4\xd8\xe8Q\xda\x8dv\x17\xb83\x14\xb5\xef6\xc2\xb7~\xd6~B\x10s\xe8\xc9\xd6"\xc9\xdd\xc52\x0eH\x11\x00\x00\x00\x00\x00\x00\x004\x94\xe8F\\\x17%\xc3\xcaVS\x98\xdbm\x8b\x9e\xa5"\t7\x92h\x85;YzB\xe5\x88\x90eUi
```

The problem I'm having is that I can't seem to find any packages that can deserialize this data. This is probably not the right place to raise this so feel free to close if so, but I was hoping you could point me in the right direction.

For reference: https://github.com/cloudflare/matched-data-cli/blob/master/src/matched_data.rs#L64

Thanks

**Comment by adamreichold** [comment]
I think you might want to write an extension using [PyO3](https://github.com/PyO3/pyo3/) to call `deserialize_encrypted_data` and then make the resulting `EncryptedData` value available to Python in whatever form is suited best, e.g. wrapping it in a custom `#[pyclass]` or trying to convert it a hierarchy of plain Python object using e.g. [pythonize](https://github.com/davidhewitt/pythonize).

**Comment by mikeylinton** [comment]
Thanks, I'll give these a look.
