### ISSUE TITLE
bincode::encode_to_vec is incompatible with bincode::serde::encode_to_vec in standard configuration

### ISSUE THREAD

**Issue by JanBeh** [bincode-org/bincode#613]
Using version `2.0.0-rc.2`, the following code:

```
fn main() {
    let array: [u8; 3] = [11, 12, 13];
    let stdcfg = bincode::config::standard();
    assert_eq!(
        bincode::encode_to_vec(&array, stdcfg).unwrap(),
        bincode::serde::encode_to_vec(&array, stdcfg).unwrap(),
    );
}
```

Fails with:

```text
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `[3, 11, 12, 13]`,
 right: `[11, 12, 13]`', src/main.rs:6:5
```

This means [`bincode::encode_to_vec`](https://docs.rs/bincode/2.0.0-rc.2/bincode/fn.encode_to_vec.html) isn't compatible with [`bincode::serde::encode_to_vec`](https://docs.rs/bincode/2.0.0-rc.2/bincode/serde/fn.encode_to_vec.html). This is highly surprising.

See also: [How can bincode distinguish between tuples and (fixed size) arrays?](https://users.rust-lang.org/t/how-can-bincode-distinguish-between-tuples-and-fixed-size-arrays/88756) on URLO.

**Comment by VictorKoenders** [comment]
That definitely seems like a bug, thanks for reporting
