### ISSUE TITLE
Derive macro breaks when using where for trait with comma

### ISSUE THREAD

**Issue by CaliViking** [bincode-org/bincode#614]
The following works:
```
#[derive(Encode, Decode)]
pub struct MyStruct<T: Clone> {
    pub a: A,
    pub b: B<T>,
}
```

Using a where statement does not work:
```
#[derive(Encode, Decode)]
pub struct MyStruct<T>
where T: Clone,
{
    pub a: A,
    pub b: B<T>,
}
```

Error:
``` expected one of `{`, lifetime, or type, found `,` ```

The issue is made worse by the Rust formatter in VS Code insisting that there is a comma after the 'where' declaration. If not, then I could just remove the comma, but it is automatically inserted

**Comment by VictorKoenders** [comment]
Created an issue upstream: https://github.com/bincode-org/virtue/issues/35, thanks for reporting!
