### ISSUE TITLE
Decode a struct with byte slice fields

### ISSUE THREAD

**Issue by boorad** [bincode-org/bincode#616]
I'm wondering what I'm doing wrong here.  

```rust
#![cfg(all(feature = "std", feature = "derive"))]

extern crate std;

#[derive(Debug, bincode::Decode, PartialEq)]
struct MyStruct {
  value: [u8; 3],
  len: u8,
}

#[test]
fn test_decode_struct_with_byte_slice() {
    let config = bincode::config::standard()
        .with_big_endian()
        .with_fixed_int_encoding();
    let start = MyStruct {
        value: [1u8, 0u8, 3u8],
        len: 2u8,
    };
    let slice = [0u8, 1u8, 2u8, 3u8];
    let (result, len): (MyStruct, usize) =
        bincode::decode_from_slice(&slice, config).unwrap();
    assert_eq!(result, start);
    assert_eq!(len, 4);
}

```

I get an `UnexpectedEnd { additional: 4 }` error.

Tracing led me to https://github.com/bincode-org/bincode/blob/v2.0.0-rc.2/src/de/mod.rs#L277 which is using a u64 (8 bytes, not 4 bytes like my slice) and errors when the size comparison fails here: https://github.com/bincode-org/bincode/blob/v2.0.0-rc.2/src/de/read.rs#L77.

What have I failed to grok here?

Thanks for the great lib!

**Comment by VictorKoenders** [comment]
Bincode will encode `[u8; 3]` as `<len><u8><u8><u8>`, so there's extra bytes in front of that slice

**Comment by boorad** [comment]
I'm not following your comment.

What of the `u64` being used in `decode_slice_len()`, which then causes https://github.com/bincode-org/bincode/blob/v2.0.0-rc.2/src/de/impls.rs#L127 to use an 8-byte slice for decoding?  If your slice is 8 bytes or less, it will always error with `UnexpectedEnd`.  Is this a bug?

How can I get `MyStruct` decoded?

**Comment by VictorKoenders** [comment]
You need to add the length of the slice to the data:
```rs
        let slice = [0u8, 0, 0, 0, 0, 0, 0, 3, 1, 0, 3, 2];
        let (result, len): (MyStruct, usize) = decode_from_slice(&slice, config).unwrap();
        assert_eq!(result, start);
        assert_eq!(len, 12);
```

But you should never have to manually edit the binary format. What is the use case where you need to manually construct a bincode slice?

**Comment by boorad** [comment]
It seems weird that the user's data and struct are the same size (4 bytes), but they have to know to pad their data up to 8 bytes because of something hidden in the bincode library.  What would a user do for data and struct size of 11 bytes?

FYI, I was using `allow_trailing_bytes()` in v1.3.3

The use case is parsing packets and payloads into structs closer to the business for use in downstream analysis.

**Comment by VictorKoenders** [comment]
Officially we don't support any other format than our own. You could play around with the config options to see if it happens to work for your format, I'm thinking `skip_fixed_array_length` and `with_variable_int_encoding` will get you a long way.

Alternatively you can manually implement a `Decode` which will give you more freedom of the data being parsed.

**Comment by boorad** [comment]
I was able to implement my own as you suggested.

`impl bincode::Decode for MyStruct {...}`

Thanks @VictorKoenders !
