### ISSUE TITLE
`encode_slice_len` as u32 support

### ISSUE THREAD

**Issue by silentEAG** [bincode-org/bincode#621]
Hi, I use bincode to (de)serialize on the client side. Unfortunately the byte length from the server side is 32 bit, so can `encode_slice_len` have `u32` support? My current solution is to customize a struct and re-implement `Encoder` and `Decoder`.

**Comment by VictorKoenders** [comment]
No, this would be a breaking change from bincode 1, and `.with_variable_int_encoding()` should compress down to the same bytes.
