### ISSUE TITLE
No appropriate DecodeError for invalid data when alloc not enabled

### ISSUE THREAD

**Issue by LLFourn** [bincode-org/bincode#622]
The only appropriate error for when you try and decode invalid bytes for your type is `DecodeError::OtherString` but this only exists when `alloc` is enabled. I think there should be an option for those without allocators. Something like  `InvalidEncoding { expected: &'static str }` would be sufficient.

**Comment by VictorKoenders** [comment]
I think this is already fixed in https://github.com/bincode-org/bincode/pull/602

**Comment by LLFourn** [comment]
Woops. That's perfect thanks.

Looking forward to the next release candidate :)
