### ISSUE TITLE
Use enum #repr field

### ISSUE THREAD

**Issue by bitdivine** [bincode-org/bincode#623]
Enum fields take 4 bytes, using the Fixedint encoding, even though most enums need at most one byte.

It is possible to use Varint encoding to save those bytes, as discussed in #157, however varint increases the size of integers that are already well matched to their types.  In a representative example in my codebase the fixedint encoding of one structure takes 100 bytes but the varint encoding takes 129 bytes.  Thus the gain from varint saving enum bytes can easily be outweighed by losses elsewhere.

Rust already supports `#[repr(u8)]` for enums.  Can not the fixint encoding use these or similar annotations?

Note: Another option would be to have a fixed enum size, but to have that enum type set in the config or provided as a type.  The same could be done with the length field.

**Comment by VictorKoenders** [comment]
This is discussed at length in #565 and #566, and there is a comment about this in the [readme](https://github.com/bincode-org/bincode#why-does-bincode-not-respect-repru8)

**Comment by bitdivine** [comment]
Thank you for the references.  As mentioned, varint as suggested in the FAQ doesn't actually reduce the message size if the integer sizes are already accurate.  However I appreciate that simplicity is a priority for you and so I have made a [fork](https://github.com/bitdivine/bincode_u8_enum) and simply changed the hard-wired u32 to u8.  This suits my use case.
