### ISSUE TITLE
Feature request: predetermined U8/U16/U32/U64 array lengths

### ISSUE THREAD

**Issue by benny-n** [bincode-org/bincode#657]
I see that a lot of issues already covered this topic, and this was eventually implemented in `bincode2`  in this PR: https://github.com/pravega/bincode2/pull/4.

Are there any plans to add the `with_array_size` function which was implemented in the aforementioned PR to `bincode` as well?

**Comment by VictorKoenders** [comment]
There are currently no plans to add `with_array_size` to bincode
