### ISSUE TITLE
Modify an Existing Configuration

### ISSUE THREAD

**Issue by thekief** [bincode-org/bincode#666]
I am currently working on a project that allows values to be written in either little or big endian form. The form of encoding is indicating by a value set inside the binary.

So basically, a simplified workflow is as follows:

**parse the header -> obtain endianness information -> parse the remaining binary**

I was wondering, if it would be possible to modify an existing configuration and potentially even propagate it back to the initial configuration.

So far I am obtaining the current configuration like this:

```rust

impl bincode::Decode for HeaderItem {
    fn decode<D: Decoder>(decoder: &mut D) -> Result<Self, DecodeError> {

        let config = decoder.config().to_owned();
        ...
```
and I am a bit lost on how to progress.

**Comment by VictorKoenders** [comment]
You are not able to change the config. For performance reason this should be a compile time constant.

However what you can do is split encoding/decoding in 2 steps:

```rs
let (header, len) = bincode::decode_from_slice(&slice, config::standard())?;
let slice = &slice[len..];

let data = if header.is_little_endian {
    bincode::decode_from_slice(&slice, config::standard().with_little_endian())?
} else {
    bincode::decode_from_slice(&slice, config::standard().with_big_endian())?
};
```

Hope this helps

**Comment by thekief** [comment]
Seems like I cannot prevent this then. I would have liked to avoid the extra handling coming with these functions. Because basically half the things I need to parse after the header are integers.

One last question in this context:

> You are not able to change the config. For performance reason this should be a compile time constant.

Is there any way (planned) to modify the standard configuration globally? Once I parsed the header I would know everything needed, allowing to use one global configuration that can be used in all further decodings.

**Comment by VictorKoenders** [comment]
> Is there any way (planned) to modify the standard configuration globally

There is not, no. With our current implementation that would require duplicating everything
