### ISSUE TITLE
Is there a way to patch 1.x? 

### ISSUE THREAD

**Issue by richardpringle** [bincode-org/bincode#685]
I have a small backwards compatible change I would like to make to the latest 1.x version. I didn't see any branch that gives me the ability to do that. Are you accepting backwards compatible patches. 

The change is tiny and only *adds* functionality:
https://github.com/richardpringle/bincode/commit/67f91e66fa77322ba3b66c8968b51b38dd112ede

Thanks in advance

**Comment by VictorKoenders** [comment]
That change would bump the MSRV from 1.19.0 to 1.31.1, and considering we are not actively maintaining 1.x I do not think we'd be interested in that change.
