### ISSUE TITLE
Add codec support for chrone

### ISSUE THREAD

**Issue by RuofengX** [bincode-org/bincode#689]
I am writing a typed wrapper for sled database using bincode-2.0.0-rc3 based on the typed-sled which use bincode-1 to do the codec thing. 

When I writing the example part of `bincode-sled`, I found that a struct which contains `chrono::DateTime<chrono::Utc>` cannot auto-derive the Encode and Decode trait, I could only turn to using a SystemTime as a work around.

source code is [here](https://github.com/RuofengX/bincode-sled/blob/41163dc72f6047b200293768bc36dfa368d0c93b/examples/advanced_search.rs#L119)

**Comment by RuofengX** [comment]
Typed-sled use derive marco of serde, which could derive the chrone::Datetime successfully.

**Comment by VictorKoenders** [comment]
> For interop with bincode’s derive feature, you can use the `#[bincode(with_serde)]` attribute on each field that implements serde’s traits.

https://docs.rs/bincode/2.0.0-rc.3/bincode/serde/index.html

Would this work?
