### ISSUE TITLE
Cannot deserialize VecDeque with structure of Decimals

### ISSUE THREAD

**Issue by hedgar2017** [bincode-org/bincode#699]
Just FYI, I'm getting `DeserializedAnyNotSupported` for a `VecDeque` of simple trading chart candlesticks.
```
pub struct Candle {
    /// The candle open time.
    pub time: u64,
    /// The candle open price.
    pub open: Decimal,
    /// The candle low price.
    pub low: Decimal,
    /// The candle high price.
    pub high: Decimal,
    /// The candle close price.
    pub close: Decimal,
    /// The vertical candle volume in secondary token units.
    pub volume: Decimal,
}
```
Basically, I cannot deserialize the same object I've just serialized.

**Comment by VictorKoenders** [comment]
Can you provide a complete example?

**Comment by hedgar2017** [comment]
@VictorKoenders of course!
The `main` function:
```
fn main() {
    let candle = rust_decimal::Decimal::new(1, 0);
    let serialized = bincode::serialize(&candle).unwrap();
    let deserialized: rust_decimal::Decimal = bincode::deserialize(serialized.as_slice()).unwrap();
    dbg!(&deserialized);
}
```
The dependencies:
```
rust_decimal = "1.34"
bincode = "1.3"
```
The panic message (of `bincode::deserialize`):
```
thread 'main' panicked at downloader/src/bug.rs:4:91:
called `Result::unwrap()` on an `Err` value: DeserializeAnyNotSupported
```

**Comment by VictorKoenders** [comment]
Looks like you need to enable a specific feature in `rust_decimal`: https://github.com/paupino/rust-decimal/blob/master/src/serde.rs#L707-L721

**Comment by hedgar2017** [comment]
> Looks like you need to enable a specific feature in `rust_decimal`: https://github.com/paupino/rust-decimal/blob/master/src/serde.rs#L707-L721

Thanks, will try.
