### ISSUE TITLE
deserialize into allocator

### ISSUE THREAD

**Issue by MarcWeber** [bincode-org/bincode#711]
I read that Rust nightly introduces allocators. There are some arena allocators like bumpalo. So eventually decode should be passed an allocator ? In my case I read millions of [u8] into bumpalo. Not important for me to fix it right now.

**Comment by adamreichold** [comment]
I think that instead of special casing allocators, there should be something like Serde's [`DeserializeSeed`](https://docs.rs/serde/latest/serde/de/trait.DeserializeSeed.html) for stateful decoding where the state could for example be an allocator.

**Comment by VictorKoenders** [comment]
There's #710 which might help with this
