### ISSUE TITLE
falling test with serde::skip_serializing_if

### ISSUE THREAD

**Issue by maks83** [bincode-org/bincode#713]
```
#[cfg(test)]
mod tests {
    #[derive(serde::Serialize, serde::Deserialize)]
    pub struct StructWithOption {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        pub opt_field: Option<usize>,
    }

    #[test]
    fn struct_with_option() {
        let val = StructWithOption {
            opt_field: None,
        };

        let config = bincode::config::standard();
        let serialized = bincode::serde::encode_to_vec(&val, config).unwrap();
        bincode::serde::decode_from_slice::<StructWithOption, _>(&serialized[..], config).unwrap();
    }
}
```

**Comment by VictorKoenders** [comment]
Unfortunately this is an known issue in serde: https://github.com/serde-rs/serde/issues/1732

Not something we can fix in bincode

**Comment by VictorKoenders** [comment]
Unfortunately this is an known issue in serde: https://github.com/serde-rs/serde/issues/1732

This will be documented in bincode 2, but the following attributes are *not* compatible with bincode. These are all serde limitations.
 
- `#[serde(flatten)]`
- `#[serde(skip)]`
- `#[serde(skip_deserializing)]`
- `#[serde(skip_serializing)]`
- `#[serde(skip_serializing_if = "path")]`
- `#[serde(tag = "...")]`
- `#[serde(untagged)]`
