### ISSUE TITLE
Different int encoding option for integers and enum variant tags

### ISSUE THREAD

**Issue by lemunozm** [bincode-org/bincode#720]
Hi!

Currently, both normal integers and enum tags are handled under the same `InternalIntEncodingConfig` option. Could that option be divided into two different options? There are a lot of protocols that use fixed ints for "normal" integers but just an `u8` for distinguish enum variants (which can be achieved in most cases with the Varint).

Is that change something in mind for this crate?

**Comment by VictorKoenders** [comment]
Unfortunately Bincode does not have support for other protocols in mind, so this is not within scope of this crate
