### ISSUE TITLE
Backward Non-compabile changes between 2.0.0-beta.3 and 2.0.0-rc3

### ISSUE THREAD

**Issue by haochenuw** [bincode-org/bincode#724]
It seems between these releases the following 
```
pub struct WriteFixedArrayLength {}
```
was removed. This is a breaking change since clients could be using the struct in their code. Could this be fixed?

**Comment by VictorKoenders** [comment]
Relevant PR: https://github.com/bincode-org/bincode/pull/625
The entire array implementation was not compatible with bincode 1, so we ripped it out and fixed that issue.

That PR ends with:
> They may be re-added in the future.

So I think this option is still open

**Comment by VictorKoenders** [comment]
One question I have is why you would want to care if bincode writes array lengths or not. What is your use case?

**Comment by haochenuw** [comment]
I am not a direct user so cannot comment on that. If the user shouldn't
care, why was this struct exposed to the public?

**Comment by VictorKoenders** [comment]
> If the user shouldn't care, why was this struct exposed to the public?

That's why we removed it 😄

**Comment by ghost** [comment]
Backwards compatibility is not something we guarantee before the final stable release of 2.0. If absolute stability is necessary the 1.0 branch should be used instead.
